<div class="popup window-bodytype">
    <div class="wrapper">
        <a id="closebodystyle__addcars" class="close" href="javascript:void(0);">×</a>
        <div class="title bold"> Выберите тип кузова </div>
        <div id="bodystylescontainer_addcars" class="wrapper-bodytype">
            <?php foreach($this->items as $item){ ?>
            
            <label class="item-bodytype" for="bodyid<?php echo $item->id; ?>__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('/images/car_icons/<?php echo $item->img; ?>');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid<?php echo $item->id; ?>__addcars" class="radio-bodytype" type="radio" value="<?php echo $item->id; ?>" name="bodyId">
                        <span><?php echo $item->name; ?></span>
                    </span>
                </label>
            
                <!--
                <label class="item-bodytype" for="bodyid5__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/kupe/suv.gif');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid5__addcars" class="radio-bodytype" type="radio" value="5" name="bodyId">
                        <span>Внедорожник / Кроссовер</span>
                    </span>
                </label>
                <label class="item-bodytype" for="bodyid8__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/kupe/van.gif');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid8__addcars" class="radio-bodytype" type="radio" value="8" name="bodyId">
                        <span>Минивэн</span>
                    </span>
                </label>
                <label class="item-bodytype" for="bodyid4__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/kupe/hatchback.gif');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid4__addcars" class="radio-bodytype" type="radio" value="4" name="bodyId">
                        <span>Хэтчбек</span>
                    </span>
                </label>
                <label class="item-bodytype" for="bodyid2__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/kupe/wagon.gif');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid2__addcars" class="radio-bodytype" type="radio" value="2" name="bodyId">
                        <span>Универсал</span>
                    </span>
                </label>
                <label class="item-bodytype" for="bodyid6__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/kupe/coupe.gif');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid6__addcars" class="radio-bodytype" type="radio" value="6" name="bodyId">
                        <span>Купе</span>
                    </span>
                </label>
                <label class="item-bodytype" for="bodyid254__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/truck/light_furgon.gif');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid254__addcars" class="radio-bodytype" type="radio" value="254" name="bodyId">
                        <span>Легковой фургон (до 1,5 т)</span>
                    </span>
                </label>
                <label class="item-bodytype" for="bodyid7__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/kupe/cabriolet.gif');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid7__addcars" class="radio-bodytype" type="radio" value="7" name="bodyId">
                        <span>Кабриолет</span>
                    </span>
                </label>
                <label class="item-bodytype" for="bodyid9__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/kupe/truck.gif');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid9__addcars" class="radio-bodytype" type="radio" value="9" name="bodyId">
                        <span>Пикап</span>
                    </span>
                </label>
                <label class="item-bodytype" for="bodyid252__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/kupe/limousine.jpg');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid252__addcars" class="radio-bodytype" type="radio" value="252" name="bodyId">
                        <span>Лимузин</span>
                    </span>
                </label>
                <label class="item-bodytype" for="bodyid28__addcars" title="">
                    <span class="image-bodytype" style="background-image: url('http://img.auto.ria./img/auto_cat/other.png');"></span>
                    <span class="description-bodytype">
                        <input id="bodyid28__addcars" class="radio-bodytype" type="radio" value="28" name="bodyId">
                        <span>Другой</span>
                    </span>
                </label>
                -->
            
            <?php } ?>
            
        </div>
        <div class="button-bar">
            <a id="choosebodystyle__addcars_btn" class="button blue" href="javascript:void(0);">Выбрать</a>
            <a id="cancelbodystyle__addcars" class="button" href="javascript:void(0);">Отмена</a>
        </div>
    </div>
</div>