<div class="popup uarr __left" style="width: 305px; " id="addyoutubevideopopup__addcars">
    <div class="wrapper">
        <a class="close" id="closeyuotubepopup__addcars" href="javascript:void(0);">x</a>

        <div class="title bold">
            Загрузить видео с YouTube
        </div>

        Скопируйте сюда ссылку на видео с сайта youtube.com.
        <a href="/help/file_471.html#video" target="_blank">Узнать подробнее</a>
        <i class="icon-view"></i>
        <p>
            <label>Ссылка на видеоролик</label>
            <input class="boxed" type="text" id="youtubeurlinput__addcars">
        </p>
        <div class="button-bar">
            <a href="javascript:void(0);" class="button blue" id="uploadyoutubevideo__addcars">Загрузить</a>
            <a href="javascript:void(0);" class="button" id="cancelyoutubepopup__addcars">Отмена</a>
        </div>
    </div>
</div>