<div id="search_auto_results" class="standart-view">
    <?php foreach ($this->list as $car) { ?>
        <div class="item">
            <div class="ticket-item" ticket_status_id="0" ticket_auto_id="11080455">
                <a name="search_auto_id_11080455"> </a>
                <div class="action-bar">
                    <a class="item icon-chips" title="Фишек нет. Что это такое?" onclick="" href="javascript:void(0);"> 0 </a>
                    <a class="item icon-star" content_type_id="1" item_id="11080455" pelement="auto_add_to_notepad" title="Добавить в блокнот" href="javascript:void(0);"></a>
                    <span class="item-check" title="Добавить к сравнению">
                        <input type="checkbox" item_id="11080455" content_type_id="1" auto_name="Audi 100 " auto_id="11080455" pelement="auto_compare_checkbox">
                        <span class="tooltip succes larr __top hide" pelement="auto_compare_popup"> </span>
                    </span>
                </div>
                <div class="content-bar">
                    <div class="ticket-photo">
                        <a class=" photo photo-135x90 " title="<?php echo $car->title; ?>" href="/auto_audi_100_11080455.html">
                            <img src="/images/photos/<?php echo $car->id; ?>/main.jpg ">
                        </a>
                        <span class="item">
                            <i class="icon-small-photo"></i>
                            7 фото
                        </span>
                    </div>
                    <div class="content">
                        <div class="head-ticket">
                            <span class="city">
                                <a title="Поиск объявлений по региону <?php echo $car->city_name; ?>." href="city/harkov/"><?php echo $car->city_name; ?></a>
                                <a class="icon-up-ticket" title="Поднять вверх при поиске" target="_blank" onclick="fishkiObj.getForm(11080455);
            _gaq.push(['_trackEvent', 'Popup_Fishek', 'Strelka', 'Search_Oldcar']);
            return false;" href="/fishki-group/"></a>
                            </span>
                            <h3 class="head-car">
                                <a title="<?php echo $car->title; ?>" href="/auto_audi_100_11080455.html"><?php echo $car->title; ?> </a>
                                1991
                            </h3>
                        </div>
                        <div class="definition-data">
                            <div class="price" currency_id="1">
                                <?php if($car->currency == 'UAH'){ ?>
                                    <span class="grey" title="UAH"><?php echo $car->price; ?> грн.</span>
                                    <span class="nbu">по курсу НБУ</span> $
                                    <strong class="green" title="USD"><?php echo intval($car->price/$this->er); ?></strong>
                                <?php } else if($car->currency == 'USD'){ ?>
                                    <span class="grey" title="UAH"><?php echo intval($car->price * $this->er);; ?> грн.</span>
                                    <span class="nbu">по курсу НБУ</span> $
                                    <strong class="green" title="USD"><?php echo intval($car->price); ?></strong>
                                <?php } ?>
                            </div>
                            <ul class="characteristic">
                                <li class="item-char" title="Тип топлива">
                                    <i class="icon-char-fuel"></i>
                                    <?php echo $car->fuel_type; ?>, <?php echo number_format($car->volume, 2, '.', ''); ?> л.
                                </li>
                                <li class="item-char" title="Пробег">
                                    <i class="icon-char-mileage"></i>
                                    <?php echo $car->mileage; ?> тыс.км.
                                </li>
                                <li class="item-char" title="Тип коробки передач">
                                    <i class="icon-char-transmission"></i>
                                    <?php echo $car->trans_type; ?>
                                </li>
                                <li class="item-char" title="Цвет кузова">
                                    <i class="icon-char-color"></i>
                                    <?php echo $car->color; ?>
                                </li>
                            </ul>
                        </div>
                        <p class="descriptions-ticket" pelement="description">Автомобиль обслужен в хорошем сотоянии.</p>
                    </div>
                    <div class="footer-ticket">
                        <span class="view-all">
                            <a href="/auto_audi_100_11080455.html">Подробно</a>
                            <i class="icon-view"></i>
                        </span>
                        <div class="charlist-data">
                            <span class="date-add" title="Объявление добавлено 03.05.2013" pvalue="22:33:45 03.05.2013" pelement="date_add">
                                <i class="icon-time-blue"></i>
                                <span class="blue" style="font-weight: bold;">Позавчера</span>
                            </span>
                            <strong class="item" title="Возможен обмен (Любой)">
                                <i class="icon-exchange"></i>
                                <span class="title-char">Обмен: Любой</span>
                            </strong>
                            <strong class="item" title="Торги">
                                <i class="icon-auction"></i>
                                <span class="title-char">Торги</span>
                            </strong>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php //foreach($this->regions as $region){ ?>
    <?php //echo $region->name; ?>
    <?php //}?>
</div>