
<div class="head-box">
    Добавление объявления: фото и подробная информация            
    <span class="area grey">
        Перейти к <a href="/?target=user" target="_blank" class="bold">Моему меню</a>
    </span>

</div>

<nav class="progressive-bar step-3">
    <?php if(isset($this->is_new) &&  $this->is_new == false && isset($this->autoId)){ ?>
        <a class="item-tab" href="/catalog/add/step/autoinfo/autoId/<?php echo $this->autoId; ?>">
            Шаг 1. <em>Объявление</em>
        </a>
    <?php } else { ?>
        <a class="item-tab" href="/catalog/add/step/autoinfo">
                Шаг 1. <em>Объявление</em>
        </a>
    <?php } ?>
    
    <?php if(isset($this->is_new) &&  $this->is_new == false && isset($this->autoId)){ ?>
        <a class="item-tab active" href="/catalog/add/step/addphoto/autoId/<?php echo $this->autoId; ?>">
            Шаг 2. <em>фото и подробная информация</em>
        </a>
    <?php } else { ?>
        <a class="item-tab active" href="javascript:void(0);">
                Шаг 1. <em>Объявление</em>
        </a>
    <?php } ?>
   
   
     <?php if(isset($this->is_new) &&  $this->is_new == false && isset($this->autoId)){ ?>
        <a class="item-tab" href="/catalog/add/step/publication/autoId/<?php echo $this->autoId; ?>">
            Шаг 3.
            <em> Публикация </em>
        </a>
    <?php } else { ?>
        <a class="item-tab" href="javascript:void(0);">
            Шаг 3.
            <em> Публикация </em>
        </a>
    <?php } ?>
</nav>



<div class="head-box line">
    <a href="http://auto.ria.ua/addauto/autoinfo/autoId/11284210" class="button mini">
        Назад                    </a>
    фото и подробная информация                </div>
<div class="form-add-auto">
    
    <?php if($this->oldSystem == true){
           echo $this->partial('/partials/old_upload.phtml', array('autoId' => $this->autoId, 'form' => $this->form, 'list' => $this->list));
       } else {
            echo $this->partial('/partials/ajax_upload.phtml', array('autoId' => $this->autoId, 'list' => $this->list));
       } 
   ?>
    <?php //echo "<pre>"; print_r($this->optionsForm); exit; ?>
  <form method="post" id="<?php echo $this->optionsForm->getId(); ?>" action="">  
      <section class="wrapper-add">
            <dl class="headbar-add characteristics">
                <dt class="head-box">
                Заполнить анкету характеристик        </dt>
                <dd class="item-help">
                    Укажите характеристику Вашего авто - это поможет покупателю выбрать именно ваш автомобиль среди всех предложений.
                    По указанным параметрам Ваш автомобиль будет участвовать в поиске        </dd>
            </dl>
            <div class="additional-add-data" id="optionscontainer__addcars">
                <div class="group-column">
                    <dl class="column">
                        <dt>
                        Безопасность  
                        </dt>
                            <?php echo $this->optionsForm->safety; ?>
                        </dl>
                </div>
                <dl class="column">
                    <dt>
                    Комфорт               
                    </dt>
                        <?php echo $this->optionsForm->comfort; ?>
                    </dl>
                    
                </dl>
                <div class="group-column">
                    <dl class="column">
                        <dt>
                        Мультимедиа                        
                        </dt>
                        <?php echo $this->optionsForm->multimedia; ?>
                    </dl>
                    <dl class="column">
                        <dt>
                        Прочее                        </dt>
                        <?php echo $this->optionsForm->other; ?>
                    </dl>
                </div>
                <dl class="column">
                    <dt>
                    Состояние                </dt>
                    
                    <?php echo $this->optionsForm->state; ?>
                    <?php echo $this->optionsForm->country; ?>
                </dl>
                <dl class="group-column">
                    <dt>
                    Управление объявлением                </dt>
                    <dd>
                        <?php echo $this->optionsForm->enable_comment; ?>
                    </dd>
                    <dd id="sendcommentsblock_addcars">
                        <?php echo $this->optionsForm->send_comments; ?>
                    </dd>
                </dl>
            </div>
        </section>
        <section class="box-panel">
            <dl class="headbar-add description">
                <dt class="head-box">
                Добавить подробное описание        </dt>
                <dd class="item-help">
                    Опишите здесь особенности Вашего авто, которые не были указаны ранее. В данном поле запрещается:<br />
                    &mdash; предлагать какие-либо услуги, не связанные с объектом продажи (пригоню под заказ, есть еще другие авто, помогу выбрать);<br />
                    &mdash; давать ссылки на какие-либо сайты или E-mail адреса, указывать номера телефонов.        </dd>
            </dl>
            <div class="add-description">
                <?php echo $this->optionsForm->description; ?>
                <p class="number-characters">
                    Осталось символов: <span id="maxdescriptionslength__addcars">1024</span>
                </p>
                
            </div>
        </section>
        <div class="submit-form-add">
            <?php echo $this->optionsForm->options_submit; ?>
        </div>
  </form>
    
  

    <p class="help-block">
        При клике на кнопку “Далее” Вы перейдете к публикации своего объявления                                                </p>

</div>
<!-- include virtual="/html/blocks/add_form/auto_buy_rotator.html"-->




<!--"/html/blocks/add_form/auto_salons_trade_in_rotator.html"-->
<!-- include virtual="/html/blocks/add_form/auto_salons_trade_in_rotator.html"-->
<!--"/html/blocks/add_form/auto_lombards_rotator.html"-->
<!-- include virtual="/html/blocks/add_form/auto_lombards_rotator.html"-->




