<div class="head-box">
    Повторная публикация: Поздравление                
    <span class="area grey">
        Перейти к <a href="/mymenu/" target="_blank" class="bold">Моему меню</a>
    </span>

</div>

<nav class="progressive-bar step-3">
    <?php if(isset($this->is_new) &&  $this->is_new == false && isset($this->auto_id)){ ?>
        <a class="item-tab active" href="/catalog/add/step/autoinfo/autoId/<?php echo $this->auto_id; ?>">
            Шаг 1. <em>Объявление</em>
        </a>
    <?php } else { ?>
        <a class="item-tab" href="/catalog/add/step/autoinfo">
                Шаг 1. <em>Объявление</em>
        </a>
    <?php } ?>
    
    <?php if(isset($this->is_new) &&  $this->is_new == false && isset($this->auto_id)){ ?>
        <a class="item-tab  active" href="/catalog/add/step/addphoto/autoId/<?php echo $this->auto_id; ?>">
            Шаг 2. <em>фото и подробная информация</em>
        </a>
    <?php } else { ?>
        <a class="item-tab" href="javascript:void(0);">
                Шаг 1. <em>Объявление</em>
        </a>
    <?php } ?>
    
    <?php if(isset($this->is_new) &&  $this->is_new == false && isset($this->auto_id)){ ?>
        <a class="item-tab active" href="/catalog/add/step/publication/autoId/<?php echo $this->auto_id; ?>">
            Шаг 3.
            <em> Публикация </em>
        </a>
    <?php } else { ?>
        <a class="item-tab" href="javascript:void(0);">
            Шаг 3.
            <em> Публикация </em>
        </a>
    <?php } ?>
</nav>

<div class="head-box line">
    <a href="http://auto.ria.ua/addauto/publication/autoId/11436210" class="button mini">
        &larr; Назад    </a>
    Публикация</div>

<div class="form-add-auto">
    <div class="grid grid-span2">
        <div class="gratters-add">

            <div class="heading">
                Поздравляем!        </div>

            <div class="title">
                <p>
                    Ваше объявление <strong><?php echo $this->data->mark_name . " " . $this->data->model_name . " " . $this->data->year; ?></strong> года                            <strong>опубликовано</strong> на <strong>1</strong> месяц <strong>до 22.08.2013</strong>. Изменения вступят в силу в течение 30 минут.
                </p>
            </div>
        </div>



        <section class="box-panel ticket-panel-gratters">
            <div class="ticket-preview">
                <div class="head-box">
                    Предварительный просмотр Вашего объявления:
                </div>
                <!--include virtual="/auto_search_preview/?auto_id=11436210&step=4"-->

                <div class="ticket-item" id="previewblock__addcars">

                    <div class="content-bar">
                        <a href="javascript:void(0);" class="photo photo-135x90" target="_blank" id="previewphoto__addcars">

                            <?php if(isset($main_photo)){ ?>
                                <img src="<?php echo '/images/photos/' . $this->auto_id . "/" . $this->main_photo; ?>" />
                            <?php } else { ?>
                                <img src="http://img.auto.ria.ua/images/no-photo/no-photo-135x90.jpg" />
                            <?php } ?>
                        </a>

                        <div class="content">

                            <div class="head-ticket">

                                <span class="city">
                                    <a href="javascript:void(0);"><?php echo $this->data->reg_name; ?></a>
                                </span>

                                <h3 class="head-car" id="previewtitle__addcars">
                                    <a href="javascript:void(0);" target="_blank"><?php echo $this->data->mark_name . " " . $this->data->model_name . " " . $this->data->version; ?></a> <?php echo $this->data->year; ?>
                                </h3>
                            </div>

                            <div class="definition-data">

                                <div class="price">
                                    <?php
                                        if($this->data->currency == 'USD')
                                            echo '$<span class="green">'.$this->data->price.'</span>';
                                        else if($this->data->currency == 'EUR')
                                            echo '€<span class="green">'.$this->data->price.'</span>';
                                        else if($this->data->currency == 'UAH')
                                            echo '<span class="green">'.$this->data->price.'</span> грн.';
                                    
                                    ?>
                                </div>

                                <ul class="characteristic">
                                    <li class="item-char" title="Тип топлива">
                                        <i class="icon-char-fuel"></i>
                                        <?php echo $this->data->fuel_type; ?>
                                        ,&nbsp;
                                        <?php echo $this->data->volume; ?> л.
                                    </li>
                                    <li class="item-char" title="Пробег">
                                        <i class="icon-mileage"></i>
                                         <?php echo $this->data->mileage; ?> тыс. км.
                                    </li>
                                    <li class="item-char" title="Тип коробки передач">
                                        <i class="icon-char-transmission"></i>
                                         <?php echo $this->data->trans_type; ?>
                                    </li>
                                    <li class="item-char" title="Цвет кузова">
                                        <i class="icon-char-color"></i>
                                        <?php echo $this->data->color; ?><?php if($this->data->metallic == 1) echo ' металлик'; ?> 
                                    </li>
                                </ul>

                            </div>


                        </div>

                        <p class="descriptions-ticket">
                            <?php echo substr($this->data->description, 0, 60); if(strlen($this->data->description) > 82) echo '...'; ?>
                        </p>

                    </div>

                </div>


                <div class="event-bar">
                    <a class="item-left" target="_blank" href="/catalog/viewmy">Перейти к просмотру объявления</a>
                    <a class="item-right" target="_blank" href="/?target=search&event=little&marka=84&model=30785" onclick="_gaq.push(['_trackEvent', 'Add_Adv', 'Click_on_Link_Search', 'Step4']);">Просмотреть объявление в поиске</a>
                </div>
            </div>
        </section>

        <div class="menu-gratters-add">
            <div class="row">
                <dl class="span6">
                    <dt class="title">
                    Вы также можете:
                    </dt>
                    <dd class="item">
                        <i class="icon-add__up-item"></i>
                        <a href="/promo_view/" onclick="_gaq.push(['_trackEvent', 'Add_Adv', 'Click_on_Link_Allocate_Adv', 'Step4']);" >Сделать Ваше обьявление более заметным</a>
                    </dd>
                    <dd class="item">
                        <i class="icon-add__add-new"></i>
                        <a href="/add_auto.html" onclick="_gaq.push(['_trackEvent', 'Add_Adv', 'Click_on_Link_Add_NewAdv', 'Step4'])">Добавить новое обьявление</a>
                    </dd>
                    <dd class="item">
                        <i class="icon-add__go-search"></i>
                        <a href="/search.html">Перейти к поиску обьявлений</a>
                    </dd>
                    <dd class="item">
                        <i class="icon-add__go-menu"></i>
                        <a href="/?target=user" onclick="_gaq.push(['_trackEvent', 'Add_Adv', 'Click_on_Link_Menu', 'Step4']);">Перейти в мое меню</a>
                    </dd>
                    <dd class="item">
                        <i class="icon-add__go-menu"></i>
                        <a href="?target=view&event=print_version&auto_id=11436210&list=1" >Распечатать листовку</a>
                    </dd>
                </dl>
                <div class="span4">
                    <div class="title">
                        Расскажите об объявлении в соц. сетях:
                    </div>
                    <div class="share-social">


                        <div class="facebook">
                            <div id="fb-root"></div>
                            <noindex><script src="http://connect.facebook.net/ru_RU/all.js#appId=223549387674070&amp;xfbml=1"></script></noindex>
                            <div class="fb-like" layout="button_count" data-href="http://auto.ria.ua/auto_volkswagen_golf_iii_11436210.html" data-send="false" data-width="225" data-show-faces="false"></div>
                        </div>
                        <div class="twitter">
                            <a href="http://twitter.com/share" data-url='http://auto.ria.ua/auto_volkswagen_golf_iii_11436210.html' class="twitter-share-button" data-lang="ru">Твитнуть</a>
                        </div>
                    </div>
                    <div class="review">
                        <a href="/newauto/Отзывы/Добавить?markaId=84" class="button blue button-icon">
                            <i class="icon-feedback-white"></i>
                            Оставить отзыв
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
