
                    
    <noindex>

    <script type="text/javascript">
        document.write('<script type="text/javascript" src="http://bn.ria.ua/www/delivery/spcjs.php?my_city=438&my_state=3&geo_state=7&geo_city=7&marka=79&model=2040&year=2008&city=438&state=3&category=1&kuzov=0&damage=2&pay=0&salon=0&price=284910.485&os='+Browser.Platform.name+'"><\x2fscript>');  
    </script> 
    
    <div id="banners_container" style="display: none;">
        <div id="300x100_1_container">
            <!--RIA baner-->
            <script type="text/javascript" language=javascript>
                <!--// <![CDATA[
                OA_show('300x100_1');
                // ]]> -->
            </script>
            <!--/RIA baner-->
        </div>
        <div id="300x100_2_container">
            <!--RIA baner-->
            <script type="text/javascript" language=javascript>
                <!--// <![CDATA[
                OA_show('300x100_2');
                // ]]> -->
            </script>
            <!--/RIA baner-->
        </div>
        <div id="380x60_container">
            <!--RIA baner-->
            <noindex>
                <script type='text/javascript'>
                    <!--// <![CDATA[
                    OA_show('380x60');
                    // ]]> -->
                </script>
            </noindex>
            <!--RIA baner-->
        </div>
        <div id="380x60_2_container" style="margin: 10px 0;">
            <!--RIA baner-->
            <script type="text/javascript" language=javascript>
                <!--// <![CDATA[
                OA_show('380x60_2');
                // ]]> -->
            </script>
            <!--/RIA baner-->
        </div>
        <div id="380x60_3_container">
            <!--RIA baner-->
            <script type="text/javascript" language=javascript>
                <!--// <![CDATA[
                OA_show('380x60_3');
                // ]]> -->
            </script>
            <!--/RIA baner-->
        </div>
        <div id="730x90_container">
            <!--RIA baner-->
            <script type="text/javascript" language=javascript>
                <!--// <![CDATA[
                OA_show('730x90');
                // ]]> -->
            </script>
            <!--/RIA baner-->
        </div>
        <div id="top_link_container" style="margin-bottom:10px;">
            <!--RIA baner-->
            <script type="text/javascript" language=javascript>
                <!--// <![CDATA[
                OA_show('top_link');
                // ]]> -->
            </script>
            <!--/RIA baner-->
        </div>
        <div id="test_container" style="text-align: center; margin-bottom: 10px;">
            <script type="text/javascript">
                <!--// <![CDATA[
                OA_show('test');
                // ]]> -->
            </script>
        </div>
    </div>
</noindex>



<style>
    .sold::after {
        background: url('http://img.auto.ria.ua/images/languages/ru/common/labels.png') no-repeat;
    }
    .sold {
        position: relative;
    }
    .sold::after {
        position: absolute;
        bottom: 0;
        right: 0;
        border: 0 dashed transparent;
        content: "";
        z-index: 200;
        width: 165px;
        height: 140px;
        background-position: 0 0;
    }
</style>


<div class="main-panel span8">
        <!--0 -->
        
        
            
                

    <nav class="navigator" id="final_page__navigator_container">
        <span class="next disabled">
            <a href="javascript:void(0);">Следующее</a>&nbsp;»
        </span>
        <span class="prev disabled">
            «&nbsp;Предыдущее
        </span>
        <div class="back-page disabled">
            <a href="javascript:void(0);">Вернуться к результатам поиска</a>
        </div>
    </nav>

            
        
        
                
<div class="heading-cars">
    <a href="javascript:void(0);" class="add-notebook" id="final_page__add_bookmark" ria_ppih_index="true" ria_ppih_title="Подсказка" ria_ppih_text="Добавляет просматриваемое объявление в &quot;блонкот&quot; в разделе &quot;мое меню&quot;. Это позволит Вам не потерять объявление и получить к нему доступ в любой момент с раздела &quot;Мое меню&quot;">
        <i class="icon-star" id="final_page__add_bookmark_icon"></i>
    </a>
    <h1 class="head-cars">
        Toyota Auris
        <span class="year">2008</span>
        
            
        
    </h1>
</div>

        
    <div class="row page-cars" id="final_page__main_info_block">
        <div class="span3 left-bar-view">
            
                
                    

<div class="price-cars">

    <div class="price-seller">
        
                <span class="price">284 910</span> грн.
                                                                                                                     
            
            </div>
            
                <div class="nbu">
                    по курсу НБУ
                </div>
                <div class="price-at-rate">
                    &euro;<span class="price">27 368</span> /
                $<span class="price" style="font-weight: bold;">35 645</span>
        </div>
    
    </div>
    <!--    .BEGIN link diagnostic  -->
    
    
         
    
    <!--    .END link diagnostic  -->
    <div id="top_link_place"></div>

                
            

            
                
                    

<div class="characteristic delimeter">
    
        
    

    
    
    

    
    
    

    
        
        
        
    

    
    
    

    
    
    

    
    
    

    
    
        <p class="item-param">
            <i class="icon-engine"></i>
                Объем двигателя:
            <strong>
                2.00 л.
            </strong>
        </p>
    
    

    
    
    

    
    
    

    
    
    

    
        
    

    
        <p class="item-param">
            <i class="icon-mileage"  id="probeg" user_id="3145629"></i>
            
                Пробег:
                <strong>
                    450
                    тыс.км
                </strong>
            
        </p>
    
    
</div>

                
            

            
                
            
            
                
                    
                    
                        
                            
                            


    


<div class="seller-data" id="black_list">

    
        <img class="photo-seller" src="http://img.auto.ria.ua/images/no-photo/avatar-50x50.gif" width="50" height="50">
    


    <dl class="info-user">

        
        <dt class="user-name">
            
                Ramzes
            
        </dt>
        

        
        
            <dd class="item">
                Город:
                <strong>
                    
                        Теребовля Тернопольская обл.
                    
                </strong>
            </dd>
        
        
       
         
        
        

        
        <dd class="item">
            Объявлений продавца:
            
                <a href="/?target=search&event=little&user_id=3145629" target="_blank"><strong id="final_page__user_ads_count">1</strong></a>
                <small class="count-offer" id="final_page__how_to_hide_link" style="display: none;"><a href="/autoseller/addpackage/?show_message=1" target="_blank">Как скрыть?</a></small>
            
        </dd>
        


        
        
            <dd class="item">
                Пользуется сайтом: <strong>
                    
                        с сегодня
                    
                </strong>
            </dd>
        
        

        
        <dd class="item">
            На сайте был: <strong id="final_page__user_last_visit" user_id="3145629">загрузка...</strong>
        </dd>
        
    </dl>


    <div class="characteristic contact-data-seller">

        <strong>
            связаться с продавцом:
        </strong>

        
              
            <div class="item-param writing-seller">
                <i class="icon-email"></i>
                <a href="javascript:void(0);" id="final_page__mail_to_seller" user_id="3145629" ria_ppih_index="true" ria_ppih_title="Подсказка" ria_ppih_text="Позволяет отправить письмо на личный e-mail продавца" ria_ppih_position_orientation="bottom">Написать сообщение</a>
            </div>
        
        


        
            
                
                    <div class="item-param">
                        <i class="icon-mobile-warning"></i>
                        <strong class="phone">(099) 120-34-99</strong>
                        
                    </div>
                
            
        
             
    </div>
</div>

                        
                    
                
            

            

            
                
                    
                        <div class="warning">
            <strong>ВНИМАНИЕ!</strong>
            <p>
                
                    AUTO.ria.ua
                 не является гарантом сделки
                и не сотрудничает с транспортными компаниями.
            </p>
            Будьте бдительны!<br>
            Не доверяйте предложениям с подозрительно
            низкой ценой 
            
                <a href="http://bezpeka.ria.ua/ru/article_22.html" target="_blank">Подробнее</a>
            
        </div>
                    
                
            

           
            
                
          
           

            
                
                    <div class="characteristic delimeter">
    <p class="item-param">
        <i class="icon-add"></i>
        <a href="/add_auto.html" class="bold green">Добавить объявление</a>
    </p>
     
    <p class="item-param" id="final_page__actions_block_edit_auto_container" style="display: none;">
        <i class="icon-edit"></i>
        <a href="/addauto/autoinfo/autoId/11471793/">Редактировать авто</a>
    </p>
     
    <p class="item-param" id="final_page__actions_block_raise_up_auto_container" style="display: none;">
        <i class="icon-up-ticket"></i>
        <a href="/fishki-group/" id="final_page__actions_block_raise_up_auto">Поднять вверх при поиске</a>
    </p>
     
    <p class="item-param" id="final_page__actions_block_republic_container" style="display: none;">
        <i class="icon-reload"></i>
        <a href="/addauto/publication/autoId/11471793/">Переопубликовать</a>
    </p>
    <p class="item-param" id="final_page__actions_block_delete_auto_container" style="display: none;">
        <i class="icon-delete"></i>
        <a href="javascript:void(0);" id="final_page__actions_block_delete_auto">Удалить в архив</a>
    </p>
    
</div>
                
            

                
                    
                        

    <div class="characteristic delimeter">
        <p class="item-param">
            <i class="icon-added-item"></i>
            Размещено: <strong id="final_page__add_date" date="2013-06-27 17:55:30">2013-06-27 17:55:30</strong>
        </p><p class="item-param">
            <i class="icon-views"></i>
            Всего просмотров: <strong id="final_page__views_counter" ria_ppih_index="true" ria_ppih_title="Подсказка" ria_ppih_text="Демонстрирует сколько потенциальных покупателей просмотрело объявление." ria_ppih_position_orientation="right">загрузка...</strong>
        </p><p class="item-param">
            <i class="icon-id-item"></i>
            ID автомобиля: <strong>11471793</strong>
        </p>

    </div>

                    
                
            

                
                 
                     <!-- include virtual="/html/common/social_network_vertical.html"-->
<div class="social-network">
    <div class="api-vk">
        <div id="vk_like"></div>
    </div>
    <div class="api-facebook" style="overflow: visible;">
        <fb:like layout="button_count" data-send="false" data-width="225" data-show-faces="false" ></fb:like>
    </div>
    <div class="api-twitter">
        <a href="http://twitter.com/share" data-url='http://auto.ria.ua/auto_toyota_auris_11471793.html' class="twitter-share-button" data-lang="ru">Твитнуть</a>
    </div>

    <div class="api-google">
        <div class="g-plusone" ></div>
    </div>
</div>

                
                

                
                    
                        <div class="characteristic">
    <p class="item-param">
        <i class="icon-star" id="final_page__actions_block_bookmark_icon"></i>
        <a href="javascript:void(0);" id="final_page__actions_block_add_to_bookmarks">Добавить в блокнот</a>
        <a href="javascript:void(0);" id="final_page__actions_block_remove_from_bookmarks" style="display: none;">Удалить из блокнота</a>
    </p>
    <div class="item-param" id="final_page__actions_block_send_complain_container">
        <i class="icon-report"></i>
        <a href="javascript:void(0);" id="final_page__actions_block_send_complain">Пожаловаться на объявление</a>
    </div>
    <p class="item-param" style="display: none;" id="final_page__actions_block_add_to_blacklist_container">
        <i class="icon-blacklist"></i>
        <a href="javascript:void(0);" id="final_page__actions_block_add_to_blacklist">Добавить в "Черный список"</a>
    </p>
    <p class="item-param">
        <i class="icon-print"></i>
        <!--a href="/?target=view&event=print_version&auto_id=11471793" class="new">Версия для печати</a-->
        <a href="/blocks_auto_view/view/final_page_print_version/11471793/2/" id="final_page__actions_block_print_version" class="new">Версия для печати</a>
    </p>
    <p class="item-param" id="final_page__action_block_print_flyer_container" style="display: none;">
        <i class="icon-print"></i>
        <a href="/?target=view&event=print_version&auto_id=11471793&list=1" target="_blank" class="new">Распечатать листовку</a>
    </p>
    <p class="item-param">
        <i class="icon-add-compare"></i>
        <a href="javascript:void(0);" id="final_page__actions_block_add_to_compare">Добавить к сравнению</a>
        <a href="javascript:void(0);" id="final_page__actions_block_compare_cars" style="display: none;">Сравнить</a>
    </p>
    <p class="item-param">
        <i class="icon-views"></i>
        <a href="/strahovanie/" target="_blank">Подобрать страховую компанию</a>
    </p>
    
        <p class="item-param">
            <i class="icon-parts-mini"></i>
            <a href="http://zapchasti.ria.ua/toyota/auris/" target="_blank">Автозапчасти Тойота Аурис</a>
        </p>
    
</div>

<p class="item-param" style="padding-left:24px;">
    <a href="javascript:void(0);" id="final_page__actions_block_choose_autogoods">Подобрать автотовары</a>
    <em class="icon-open"></em>
</p>

<div id="final_page__actions_block_autogoods_container" class="characteristic" style="display: none; height: 0px; overflow-y: hidden;">
    <p class="item-param">
        <i class="icon-tyres"></i>
        <a href="http://market.auto.ria.ua/shina" target="_blank">Подобрать шины</a>
    </p>
    <p class="item-param">
        <i class="icon-disk"></i>
        <a href="http://market.auto.ria.ua/diski" target="_blank">Подобрать диски</a>
    </p>

</div>

                    
                
            
        </div>

        <div class="span5">
            <div class="gallery-order">
                <div>
                    
                        <div class="photo-380x250 main-photo " onclick="window.open('/old/auto_photo/viewphoto/11471793/', '_blank', 'width=800,height=600,scrollbars=yes'); _gaq.push(['_trackEvent', 'Photos', 'Click_on_Main_photo', 'Ad_Page']);">
    
    
    
        <img src="http://img.auto.ria.ua/images/no-photo/no-photo-380x250.jpg"/>
    
</div>
<div class="count-photo__order">
    
        <div class="count-photo">
            
                Нет фото Toyota Auris 2008
           
       </div>
    
</div>
<div class="preview-gallery">
    
        
    
</div>


    <div id="380x60_place"></div>



    
        <div class="cars-review" id="final_page__reviews_block">
    <a href="/newauto/Отзывы/Toyota" target="_blank" class="bold">Отзывы о Toyota:</a>
    <span class="rating-review rr2">
        <a class="itemstar on" href="/newauto/Отзывы/Добавить?markaId=79" target="_blank"></a>
        <a class="itemstar on" href="/newauto/Отзывы/Добавить?markaId=79" target="_blank"></a>
        <a class="itemstar on" href="/newauto/Отзывы/Добавить?markaId=79" target="_blank"></a>
        <a class="itemstar half" href="/newauto/Отзывы/Добавить?markaId=79" target="_blank"></a>
        <a class="itemstar " href="/newauto/Отзывы/Добавить?markaId=79" target="_blank"></a>
    </span>
    <span class="allotted">
        <strong>3.1</strong> из <strong>5</strong>
    </span>
</div>
    



    
        
    



    <div class="panel-notice" id="final_page__remarks_add_container">
        <i class="icon-remark"></i>
        <a href="javascript:void(0);" id="final_page__remarks_add">Оставить заметку</a>
        <a href="javascript:void(0);" id="final_page__remarks_edit" style="display: none;">Редактировать заметку</a>
        <span id="final_page__remarks_delimiter" style="display: none;">|</span>
        <a href="javascript:void(0);" id="final_page__remarks_delete" style="display: none;" class="red">удалить</a>
    </div>
    <div class="remarka" id="final_page__remarks_text_container" style="display: none;">
        <div class="warning uarr __right" id="final_page__remarks_text"></div>
    </div>

                    

                    
                        
                            

<section class="box-panel">
    <div class="title bold">
        Описание Toyota Auris 2008
    </div>
    <div class="box-panel rocon">
        
        
        
        <p class="description-order">
            
                <a href="http://www.ria.ua/adv/search_text/Toyota/" title="Toyota" target="_blank">Toyota</a> Auris, 2008  года, г. Теребовля
            
        </p>
        
            
        
    </div>
</section>
<div id="380x60_2_place"></div>
<p>
    <a href="javascript:void(0);" id="final_page__to_similar_ads">Похожие обьявления</a>
</p>
<div id="380x60_3_place"></div>

                        
                    
                    
                        
                            <section class="box-panel">
    <div class="title bold">
        
            Страховые компании
        
    </div>
    <div class="box-panel rocon">
        <div class="informer__insurance">
            
                <a 
                        href="/golink/?http://ingo.kiev.ua" target="_blank"
                     class="item" onclick="_gaq.push(['_trackEvent', 'Avtostrahovanie', 'Click_on_Logo_[297]_Страховая Компания «ИНГО Украина»', 'Page_Ad']);">
                    <img src="http://img.ria.ua/photos/auto/autoinsurance/0/2/297/297s.jpg" width="100" alt="" title=""> 
                <span class="name">Страховая Компания «ИНГО Украина»</span>
                </a>
              
              
               
            
                <a 
                        href="/golink/?http://osgpo.com.ua/" target="_blank"
                     class="item" onclick="_gaq.push(['_trackEvent', 'Avtostrahovanie', 'Click_on_Logo_[316]_OSGPO.com.ua', 'Page_Ad']);">
                    <img src="http://img.ria.ua/photos/auto/autoinsurance/0/3/316/316s.jpg" width="100" alt="" title=""> 
                <span class="name">OSGPO.com.ua</span>
                </a>
              
              
               
            
                <a 
                        href="/golink/?http://avto-civilka.kiev.ua/" target="_blank"
                     class="item" onclick="_gaq.push(['_trackEvent', 'Avtostrahovanie', 'Click_on_Logo_[352]_Автогражданка-Автоцивилка', 'Page_Ad']);">
                    <img src="http://img.ria.ua/photos/auto/autoinsurance/0/3/352/352s.jpg" width="100" alt="" title=""> 
                <span class="name">Автогражданка-Автоцивилка</span>
                </a>
              
              
               
            
        </div>
    </div>
</section>
                        
                    
                </div>
            </div>
        </div>
    </div>

    
        
            
        

        
            
        
        
            <section class="box-panel" id="final_page__comments_container">
    
    



    
        
            <p class="add-comment">
                <a href="javascript:void(0);" class="button green large" id="final_page__add_comment">Добавить комментарий</a>
            </p>
        
    





</section>

        
    

    
        
    <section class="box-panel rocon">
        <div class="head">
            Новые авто
            <a class="area" href="/newauto/search" target="_blank" title="Перейти к поиску новых авто">Смотреть все</a>
        </div>
        <div class="informer__newcars">
            
                <div class="item ">
                    <div class="details-newcar">
                        <a  target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_Logo_[275]_auto_[801669]', location.search?'Final_Oldcar':'Search_Oldcar']);" class="photo-85x56" href="/golink/?http://www.toyota.com.ua/auto/auris">
                            <img alt="Toyota Auris New  1.33 MT City " src="http://img.ria.ua/photos/auto/new_auto_storage/19/1975/197540/197540s.jpg" width="85" title="Toyota Auris ">
                        </a>
                        <dl class="subscribe-item">
                            <dt class="title">
                                <a target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_Name_[275]_auto_[801669]', location.search?'Final_Oldcar':'Search_Oldcar']);" href="/golink/?http://www.toyota.com.ua/auto/auris">
                                    Toyota Auris New  1.33 MT City 
                                </a>
                            </dt>
                            <dd class="rows price">
                                <strong class="green">149 714</strong> грн.
                            </dd>
                        </dl>
                    </div>
                    <div class="details">
                        <div class="details-layer">
                            <div class="all-images">
                                <a target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_Logo_[275]_auto_[801669]', location.search?'Final_Oldcar':'Search_Oldcar']);" href="/golink/?http://www.toyota.com.ua/auto/auris">
                                    <img alt="Toyota Auris New  1.33 MT City " src="http://img.ria.ua/photos/auto/new_auto_storage/19/1975/197540/197540m.jpg" title="Toyota Auris ">
                                </a>
                            </div>
                            <div class="car-type">
                                Тип кузова: <strong>Комби (хэтчбек)</strong><br>
                                Тип топлива: <strong>Бензин</strong><br>
                                Кол-во дверей: <strong>5</strong><br>
                                Тип привода: <strong>Передний</strong><br>
                                Коробка передач: <strong>Механическая</strong><br>
                                Обьем двигателя, см3: <strong>1329</strong><br>
                                <span class="boxed view-all">
                                    <a target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_More_[275]_auto_[801669]', location.search?'Final_Oldcar':'Search_Oldcar']);" href="/golink/?http://www.toyota.com.ua/auto/auris">
                                        Подробно
                                    </a>
                                    <i class="icon-view"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            
                <div class="item ">
                    <div class="details-newcar">
                        <a  target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_Logo_[1285]_auto_[852222]', location.search?'Final_Oldcar':'Search_Oldcar']);" class="photo-85x56" href="/newauto/Автосалон/Киев/SaleCars /Toyota/Auris/26971/852222/1285/">
                            <img alt="Toyota Auris New  1.33 MT City " src="http://img.ria.ua/photos/auto/new_auto_storage/19/1975/197540/197540s.jpg" width="85" title="Toyota Auris ">
                        </a>
                        <dl class="subscribe-item">
                            <dt class="title">
                                <a target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_Name_[1285]_auto_[852222]', location.search?'Final_Oldcar':'Search_Oldcar']);" href="/newauto/Автосалон/Киев/SaleCars /Toyota/Auris/26971/852222/1285/">
                                    Toyota Auris New  1.33 MT City 
                                </a>
                            </dt>
                            <dd class="rows price">
                                <strong class="green">149 805</strong> грн.
                            </dd>
                        </dl>
                    </div>
                    <div class="details">
                        <div class="details-layer">
                            <div class="all-images">
                                <a target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_Logo_[1285]_auto_[852222]', location.search?'Final_Oldcar':'Search_Oldcar']);" href="/newauto/Автосалон/Киев/SaleCars /Toyota/Auris/26971/852222/1285/">
                                    <img alt="Toyota Auris New  1.33 MT City " src="http://img.ria.ua/photos/auto/new_auto_storage/19/1975/197540/197540m.jpg" title="Toyota Auris ">
                                </a>
                            </div>
                            <div class="car-type">
                                Тип кузова: <strong>Комби (хэтчбек)</strong><br>
                                Тип топлива: <strong>Бензин</strong><br>
                                Кол-во дверей: <strong>5</strong><br>
                                Тип привода: <strong>Передний</strong><br>
                                Коробка передач: <strong>Механическая</strong><br>
                                Обьем двигателя, см3: <strong>1329</strong><br>
                                <span class="boxed view-all">
                                    <a target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_More_[1285]_auto_[852222]', location.search?'Final_Oldcar':'Search_Oldcar']);" href="/newauto/Автосалон/Киев/SaleCars /Toyota/Auris/26971/852222/1285/">
                                        Подробно
                                    </a>
                                    <i class="icon-view"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            
                <div class="item last">
                    <div class="details-newcar">
                        <a  target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_Logo_[1253]_auto_[840099]', location.search?'Final_Oldcar':'Search_Oldcar']);" class="photo-85x56" href="/newauto/Автосалон/Ужгород/Тойота Центр Ужгород «Карат Мотор»/Toyota/Auris/26971/840099/1253/">
                            <img alt="Toyota Auris New  1.33 MT City " src="http://img.ria.ua/photos/auto/new_auto_storage/19/1975/197540/197540s.jpg" width="85" title="Toyota Auris ">
                        </a>
                        <dl class="subscribe-item">
                            <dt class="title">
                                <a target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_Name_[1253]_auto_[840099]', location.search?'Final_Oldcar':'Search_Oldcar']);" href="/newauto/Автосалон/Ужгород/Тойота Центр Ужгород «Карат Мотор»/Toyota/Auris/26971/840099/1253/">
                                    Toyota Auris New  1.33 MT City 
                                </a>
                            </dt>
                            <dd class="rows price">
                                <strong class="green">149 713</strong> грн.
                            </dd>
                        </dl>
                    </div>
                    <div class="details">
                        <div class="details-layer">
                            <div class="all-images">
                                <a target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_Logo_[1253]_auto_[840099]', location.search?'Final_Oldcar':'Search_Oldcar']);" href="/newauto/Автосалон/Ужгород/Тойота Центр Ужгород «Карат Мотор»/Toyota/Auris/26971/840099/1253/">
                                    <img alt="Toyota Auris New  1.33 MT City " src="http://img.ria.ua/photos/auto/new_auto_storage/19/1975/197540/197540m.jpg" title="Toyota Auris ">
                                </a>
                            </div>
                            <div class="car-type">
                                Тип кузова: <strong>Комби (хэтчбек)</strong><br>
                                Тип топлива: <strong>Бензин</strong><br>
                                Кол-во дверей: <strong>5</strong><br>
                                Тип привода: <strong>Передний</strong><br>
                                Коробка передач: <strong>Механическая</strong><br>
                                Обьем двигателя, см3: <strong>1329</strong><br>
                                <span class="boxed view-all">
                                    <a target="_blank" onclick="_gaq.push(['_trackEvent', 'NewAuto', 'Click_on_More_[1253]_auto_[840099]', location.search?'Final_Oldcar':'Search_Oldcar']);" href="/newauto/Автосалон/Ужгород/Тойота Центр Ужгород «Карат Мотор»/Toyota/Auris/26971/840099/1253/">
                                        Подробно
                                    </a>
                                    <i class="icon-view"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            
        </div>
    </section>   


    

    
        
            <div class="informer__market">

    <div class="left-bar__market">

        <dl class="head__informer">

                            <dt class="title__informer">Товары для</dt>
                <dd class="content__informer">
                    <a href="http://market.auto.ria.ua/search_for_auto/Toyota/Auris/?utm_source=autoria&utm_medium=informer&utm_campaign=marketmain" target="_blank" class="link__informer" >Toyota Auris</a>
                </dd>
                    </dl>

        <div class="boxed">

            <ol class="unordered-list list__market">
                <li>
                    <a href="http://market.auto.ria.ua/shina?utm_source=autoria&utm_medium=informer&utm_campaign=marketcategory">шины</a>
                </li>
                <li>
                    <a href="http://market.auto.ria.ua/diski?utm_source=autoria&utm_medium=informer&utm_campaign=marketcategory">диски</a>
                </li>
                <li>
                    <a href="http://market.auto.ria.ua/car_seats?utm_source=autoria&utm_medium=informer&utm_campaign=marketcategory">автокресла</a>
                </li>
            </ol>
            <ol class="unordered-list list__market">
                <li>
                    <a href="http://market.auto.ria.ua/?event=search&rubric_id=293&type_search=1&str_search=&option%5B313%5D=63&option%5B314%5D=826&utm_source=autoria&utm_medium=informer&utm_campaign=marketcategory">коврики</a>
                </li>
                <li>
                    <a href="http://market.auto.ria.ua/?event=search&rubric_id=294&type_search=1&str_search=&option%5B313%5D=63&option%5B314%5D=826&utm_source=autoria&utm_medium=informer&utm_campaign=marketcategory">чехлы</a>
                </li>
                <li>
                    <a href="http://market.auto.ria.ua/?event=search&rubric_id=295&type_search=1&str_search=&option%5B313%5D=63&option%5B314%5D=826&utm_source=autoria&utm_medium=informer&utm_campaign=marketcategory">фаркопы</a>
                </li>
            </ol>
        </div>
    </div>


    <div class="wrapper__market">
        <div class="boxed">
                                                                                            

                                                                
                    <div class="item__market">
                        <a class="photo__market" href="http://market.auto.ria.ua/diski-item-50922.html?utm_source=autoria&utm_medium=informer&utm_campaign=markettovar" title="Диски">
                            <img class="img__market" alt="Диски" width="82" src="http://img.ria.ua/photos/auto/treba/25/2518/251837/251837s.jpg" />
                        </a>
                        <div class="content__market">
                            <a class="head__market" href="http://market.auto.ria.ua/diski-item-50922.html?utm_source=autoria&utm_medium=informer&utm_campaign=markettovar" title="Диски">
                                RS 280 HS
                            </a>

                            <p class="desc__market">Диски</p>
                            <div class="price__market">
                                <span class="count__market">597</span>грн.
                            </div>
                        </div>
                    </div>

                                                                                                            

                                                                
                    <div class="item__market">
                        <a class="photo__market" href="http://market.auto.ria.ua/mats-item-89145.html?utm_source=autoria&utm_medium=informer&utm_campaign=markettovar" title="Чехлы на сиденья ">
                            <img class="img__market" alt="Чехлы на сиденья " width="82" src="http://img.ria.ua/photos/auto/treba/26/2615/261527/261527s.jpg" />
                        </a>
                        <div class="content__market">
                            <a class="head__market" href="http://market.auto.ria.ua/mats-item-89145.html?utm_source=autoria&utm_medium=informer&utm_campaign=markettovar" title="Чехлы на сиденья ">
                                Toyota Auris 2008
                            </a>

                            <p class="desc__market">Чехлы на сиденья </p>
                            <div class="price__market">
                                <span class="count__market">615</span>грн.
                            </div>
                        </div>
                    </div>

                            
        </div>
    </div>


</div>
        
    

    
        
            
    <section class="box-panel rocon">
        <p>
            <strong>СРОЧНЫЙ  ВЫКУП </strong>легковых авто украинской регистрации на выгодных для Вас условиях.&nbsp;<br />
(066)049-69-72, (067) 346-13-96, (050) 750-39-11,<strong>avtovikupsergey@mail.ru, http://avtoturbo.com/</strong>&nbsp;
        </p>
    </section>

    <section class="box-panel rocon">
        <p>
            Срочный<strong> ВЫКУП АВТО</strong> укр. регистрации. Не старше 2000г. Реальная цена. Мгновенный расчет. Выкуп кредит.авто 099 4334343, 067 6173214, 050 4625055, <strong>www.auto-dealer.com.ua</strong>
        </p>
    </section>

    <section class="box-panel rocon">
        <p>
            <strong>ТЕРМІНОВИЙ ВИКУП</strong> автомобілів на вигідних умовах (укр.реєстрації з 2000р.в.)&nbsp;<strong>Автосалон &quot;РІК АВТО&quot;,</strong>&nbsp;тел: (093)1595050; (067)1834433; (066)0295129; (095)3834433; <strong>http://rikauto.com.ua/</strong>
        </p>
    </section>

        
    

    
        
            

        
    

    
        
            
        

        
            <section class="box-panel">
    <h4 class="head">
        Последние новости:
    </h4>
    <div class="panel-wrap">
        <ol class="unordered-list">
            
                <li class="item-news">
    <a href="/news/actions/207939" target="_blank">Специальное ограниченное предложение от дилерского центра Peugeot "ВиДи Авеню"</a>
    <em class="date">27.06.2013</em>
</li>

            
                <li class="item-news">
    <a href="/news/events/207969" target="_blank">Формула-1: Марк Уэббер уходит из Королевских гонок</a>
    <em class="date">27.06.2013</em>
</li>

            
                <li class="item-news">
    <a href="/news/journals/207970" target="_blank">Онлайн-журнал «AUTO.ria.ua на выходные». Выпуск №21</a>
    <em class="date">27.06.2013</em>
</li>

            
                <li class="item-news">
    <a href="/news/actions/207971" target="_blank">Львів визначив своїх фіналістів конкурсу  «Кращий водій України 2013»</a>
    <em class="date">27.06.2013</em>
</li>

            
                <li class="item-news">
    <a href="/news/actions/207972" target="_blank">KIA Драйв Тур 2013: приготовьтесь к яркому тест-драйву!</a>
    <em class="date">27.06.2013</em>
</li>

            
        </ol>
    </div>
</section>
        
    

    
        <section class="box-panel">
    <h4 class="head">
        Модельный ряд Toyota на AUTO.ria.ua
    </h4>
    <div class="panel-wrap">
        <div class="catalog-list count-column-two">
            
                <ol class="unordered-list">
                    
                        <li>
                            Продажа <a href="/car/toyota/4Runner/">Тойота 4 Ранер</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Avensis/">Тойота Авенсис</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Avensis Verso/">Тойота Авенсис Версо</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Camry/">Тойота Камри</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Carina/">Тойота Карина</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Carina E/">Тойота Carina E</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Celica/">Тойота Селика</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Corolla/">Тойота Королла</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Corolla Verso/">Тойота Королла Версо</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Corona/">Тойота Корона</a>
                        </li>
                    
                </ol>
            
                <ol class="unordered-list">
                    
                        <li>
                            Продажа <a href="/car/toyota/Cressida/">Тойота Кресида</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Crown/">Тойота Краун</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Land Cruiser/">Тойота Land Cruiser</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/MR2/">Тойота МР2</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Paseo/">Тойота Пасео</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Picnic/">Тойота Пикник</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Previa/">Тойота Привеа</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Prius/">Тойота Приус</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Rav 4/">Тойота РАВ 4</a>
                        </li>
                    
                        <li>
                            Продажа <a href="/car/toyota/Space Cruiser/">Тойота Space Cruiser</a>
                        </li>
                    
                </ol>
            
        </div>
        <div class="view-all">
            <a href="/car/toyota/">Смотреть все</a>
            <i class="icon-view"></i>
        </div>
    </div>
</section>
    

    
        <a href="javascript:void(0);" id="final_page__to_top" class="navigator text-c">
            Подняться вверх
            <i class="icon-up-blue"></i>
        </a>
    

    
        <div class="window-fixed hide" id="houses_popup"></div>
    

    
        <div class="window-fixed" id="final_page__exchange_popup_container" style="display: none;">
            <div class="mount-iframe">
                <iframe></iframe>
            </div>
            <div class="popup window-exchange">
                <div class="wrapper" id="final_page__exchange_popup_wrapper"></div>
            </div>
        </div>
    

    
        <div class="window-fixed" id="final_page__auctions_popup_container" style="display: none;">
            <div class="mount-iframe">
                <iframe></iframe>
            </div>
            <div class="popup window-auction">
                <div class="wrapper" id="final_page__auctions_popup_wrapper"></div>
            </div>
        </div>
    


    
    <div class="window-absolute" id="final_page__autotest_popup_container" style="display: none;">
            <div class="mount-iframe">
                <iframe></iframe>
            </div>
            <div class="popup window-fishki" id="final_page__autotest_popup">
                <div class="wrapper-fishki" id="final_page__autotest_popup_wrapper"></div>
            </div>
    </div>

    


    
     <div class="mount-window-fixed" id="final_page__autotestdrive_popup_container" style="display: none;">
        <div class="window-fixed">
            <div class="mount-iframe">
               <iframe></iframe>
            </div>
        </div>
        <div class="popup window-testdrive" id="final_page__autotestdrive_popup">
            <div class="wrapper" id="final_page__autotestdrive_popup_wrapper"></div>
        </div>
    </div>

    

    
         <div id="final_page__thanks_popup_container" class="popup popup__sold uarr __left" style=" display: none; width:320px;left:150px;top:240px;">
                    <div class="wrapper grid" id="final_page__thanks_popup_right_shadow">

                    </div>
        </div>
    
</div>

                      
  
  
  
  
  
  
  
  
  
  
  
  
  

  

  

  

  

  

   

    

  

  

  

  

   
       
       
       
  

    

     


  

 

<!--    .BEGIN Right Panel    -->

<div class="right-panel span4">
  
    
<ol class="statistic-addcars">
    <li class="item left">
        новых
        <span class="allotted">
            + <a href='/last/visit/' class="bold" type="visit">0</a>
        </span>
    </li>
    <li class="item right">
        за день <a href='/last/today/' class="bold" type="day">6765</a>
    </li>
    <li class="item center">
        за час <a href='/last/hour/' class="bold" type="hour">752</a>
    </li>
    <noindex>
        <script>
            Ria_Autoloader.loadClass('Ria_Common_Controller','1.0',function() {
                var Ria_Auto_Right_Ads_Counts = new Class({
                    Implements: [Events, Options],
                    //-------------------
                    options: {
                        new_from_last_visit_container : '.statistic-addcars .allotted a',
                        last_auto_id : 0
                    },
                    //-------------------
                    initialize : function(options) {
                        Ria_Autoloader.registerLocalClass('Ria_Auto_Right_Ads_Counts');
                        this.setOptions(options);
                        this.setupEvents();
                    },
                    //-------------------
                    setupEvents : function() {
                      Ria_Autoloader.loadClass('Ria_Common_Controller','1.5',function() {
                        Ria_Common_Controller_Class.addEvent('reload_auto_adv_counters',function(data) {
                            this.reSetupLastAutoId(data.last_auto_id);
                            this.repaintCounters(data);
                        //    Ria_Common_Controller_Class.console('Right -> reload_auto_adv_counters:',data);
                        }.bind(this));
                      });
                        var last_auto_id =  Cookie.read('sess_auto_id');
                        if (!last_auto_id){
                            last_auto_id = this.options.last_auto_id;
                            this.reSetupLastAutoId(last_auto_id);
                        }
                        var elem = $$(this.options.new_from_last_visit_container);
                        var difference = 0;
                        if (elem && this.options.last_auto_id > last_auto_id ) {
                            difference = (this.options.last_auto_id - last_auto_id);
                            Array.each(elem, function(item, index) {
                                item.set('text', difference)
                            });
                        }
                    },
                    //-------------------
                    reSetupLastAutoId : function(last_auto_id) {
                        this.options.last_auto_id = last_auto_id;
                        Cookie.write('sess_auto_id', last_auto_id);
                    },
                    //-------------------
                    repaintCounters : function(data) {
                        $$(this.options.new_from_last_visit_container).set('text',0)
                        $$('.statistic-addcars li.item a[type=hour]')[0].set('text',data.count_per_hour);
                        $$('.statistic-addcars li.item a[type=day]')[0].set('text',data.count_per_day);
                    }
                });
                var Ria_Auto_Right_Ads_Counts_Class = new Ria_Auto_Right_Ads_Counts({
                    last_auto_id : 11471964
                });
            });
        </script>
    </noindex>
</ol>

  

    

    
        <noindex>
    <script>
        function detectPhotoIMG() {

            var picSRC = '';
            var picSRC1 = $('pagerNewCars').getElement('img').src;
            var picSRC2 =  $('pagerUsedCars').getElement('img').src;

            if(isVisibleDOMobject(document.getElementById('ria-tab-new'))) {
                    // ??? ??? visible
                    picSRC = picSRC1;
            }
            else {
                    // ??? ??? hidden
                    picSRC = picSRC2;
            }
            return typeof(picSRC)!="undefined" ? picSRC : '';
        }

        function isVisibleDOMobject(obj) {
        if (obj == document) return true
            if (!obj) return false
            if (!obj.parentNode) return false
            if (obj.style) {
                if (obj.style.display == 'none') return false
                if (obj.style.visibility == 'hidden') return false
            }

            //Try the computed style in a standard way
            if (window.getComputedStyle) {
                var style = window.getComputedStyle(obj, "")
                if (style.display == 'none') return false
                if (style.visibility == 'hidden') return false
            }

            //Or get the computed style using IE's silly proprietary way
            var style = obj.currentStyle
            if (style) {
                if (style['display'] == 'none') return false
                if (style['visibility'] == 'hidden') return false
            }

            return isVisibleDOMobject(obj.parentNode)

        }
    </script>
</noindex>


    <!--    .BEGIN BANNER PLACE 300    -->

    <div class="banner-place-300">
        
        <div id="adriver_banner"></div>
        <noindex>
            <script type="text/javascript" language=javascript>
            new adriver.Plugin.require('old.adriver').onLoadComplete(function(){
                new adriver('adriver_banner', {sid:102878,bt:52,pz:2,bn:0});
                if ($('adriver_banner').get('html')!='') $('right_advertisemrnt').setStyle('display','block');
            });
            window.addEvent('domready', function() {
                setTimeout(function() {if ($('adriver_banner').get('html')!='')  $('right_advertisemrnt').setStyle('display','block');}, 1000)
            });
            </script>
        </noindex>
        

        
            <div id="right_advertisemrnt" style="font-size: 11px; display: none;" align="right"><a href='/price'>На правах рекламы</a></div>
        
    </div>

    <!--    .END BANNER PLACE 300    -->
    

     
        
    <!--    <div class="box-panel" id="right_currencies_panel" onclick="$$('div#right_currencies_panel div.head + div.panel').toggleClass('hide');" >-->
    <div class="box-panel" id="right_currencies_panel">
        <div class="head head-financeua">
            <i class="icon-head-finance"></i>
            <a href="javascript:void(0);" >Курс валют</a>

            <div class="financeua-mini hide">

                <strong class="item" title="-10.6701">
                    <span class="red">€</span>
                    10.67
                </strong>
                <strong lass="item" title="-8.1506">
                    <span class="red">$</span>
                    8.15
                </strong>

            </div>

            <i class="icon-close"></i>

        </div>
        <div class="panel">
            <div class="financeua">
                <a class="link-finance" href="http://finance.ua/"target="_blank"></a>
                    
                        
                            <dl class="row head-row">
                                <dt class="span1" title="18:05:34 27.06.2013">
                                    <i class="icon-clock"></i>
                                    18:05
                                </dt>
                                <dd class="span1">Покупка</dd>
                                <dd class="span1">Продажа</dd>
                            </dl>
                        
                        <dl class="row">
                            <dt class="span1">EUR</dt>
                            <dd class="span1">
                                <strong title="-10.5466">
                                    10.54
                                </strong>
                                <em>
                                
                                    &darr;
                                
                                </em>
                            </dd>
                            <dd class="span1">
                                <strong title="-10.6701">
                                    10.67
                                </strong>
                                <span class="hide">10.6701</span>
                                <em>
                                    &darr;
                                </em>
                            </dd>
                        </dl>
                
                        
                        <dl class="row">
                            <dt class="span1">USD</dt>
                            <dd class="span1">
                                <strong title="-8.1214">
                                    8.12
                                </strong>
                                <em>
                                
                                    &darr;
                                
                                </em>
                            </dd>
                            <dd class="span1">
                                <strong title="-8.1506">
                                    8.15
                                </strong>
                                <span class="hide">8.1506</span>
                                <em>
                                    &darr;
                                </em>
                            </dd>
                        </dl>
                
            </div>
        </div>
    <noindex>
        <script type="text/javascript">
            Ria_Autoloader.loadClass('Hash.Cookie','1.6',function() {

                var settings = new Hash.Cookie('siteSettings', {path: '/', duration:'365'});
                var arr = [];
                var tog = true;
                if(settings.hash.currBoxShort){
                    if(settings.hash.currBoxShort[0]){
                        tog = false;
                    }else{
                        tog = true;
                    }
                }else{
                    arr[0] = false;
                    settings.set('currBoxShort', arr);
                    tog = true;
                }

                Ria_Autoloader.loadClass('Ria_Common_Visual_Spoilers_Smooth','1.32',function() {
                    new Ria_Common_Visual_Spoilers_Smooth({
    //                    container : '#right_pannel_about_us',
                        action_element_selector : '#right_currencies_panel .head ',
                        target_element_selector : '#right_currencies_panel > .panel',
                        events : {
                            after : {
                                close : function(){
                                    $$('#right_currencies_panel .head > .financeua-mini')[0].addClass('hide');
                                    $$('#right_currencies_panel .head > + i')[0].removeClass('icon-open').addClass('icon-close');
                                    var calculator_panel = $('panel_calculator');
                                    if (calculator_panel) {
                                        calculator_panel.removeClass('hide');
                                    }

                                    arr[0] = true;
                                    settings.set('currBoxShort', arr);
                                },
                                open : function() {
                                    $$('#right_currencies_panel .head > .financeua-mini')[0].removeClass('hide');
                                    $$('#right_currencies_panel .head > + i')[0].removeClass('icon-close').addClass('icon-open');
                                    var calculator_panel = $('panel_calculator');
                                    if (calculator_panel) {
                                        calculator_panel.addClass('hide');
                                    }
                                    arr[0] = false;
                                    settings.set('currBoxShort', arr);
                                }
                            }
                        },
                        toggle_at_init : tog
                    });

                });
            },{js_folder:'js/MooTools'});
        </script>
    </noindex>
        <div id="panel_calculator" class="panel">
    <div class="" id="calculator_link" >
        <a id="calculator_link_a" href="javascript:void(0);" >Валютный калькулятор</a>
        <i id="icon" class="icon-open"></i>
    </div>
    <div id="calculator" class="calculator hide">
        <div class="title">Валютный калькулятор</div>
        <table class="calc">
            <tbody>
            <tr>
                <td>
                    <input  id="js_in_valutata" type="text" value="100" class="span1">
                </td>
                <td>
                    <select id="curv1" class="changablekurs">
                        <option value="3">$</option>
                        <option value="2">€</option>
                        <option value="1">грн</option>
                        </select>
                </td>
                <td style="line-height: 26px">=</td>
                <td>
                    <select id="curv2" class="changablekurs">
                        <option value="1">грн</option>
                        <option value="3">$</option>
                        <option value="2">€</option>
                    </select>
                </td>
                <td>
                    <input id="js_out_valutata" type="text" value="" class="span1" readonly="readonly">
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    
</div>

<script>
    var Ria_Auto_MainPage_Calculator = {};
    Ria_Autoloader.loadClass('Ria_Auto_MainPage_Calculator','1.32',function() {
        Ria_Auto_MainPage_Calculator = new Ria_Auto_MainPage_Calculator({});

    });
    Ria_Common_Visual_Spoilers_Smooth1 ={};
    Ria_Autoloader.loadClass('Ria_Common_Visual_Spoilers_Smooth','1.0',function() {
        Ria_Common_Visual_Spoilers_Smooth1 = new Ria_Common_Visual_Spoilers_Smooth({
                    container : '#panel_calculator',
            action_element_selector : '#calculator_link',
            target_element_selector : '#calculator',
            events : {
                after : {
                    close : function(){
                        $('calculator').removeClass('hide');
                        $('calculator_link_a').set('html','Скрыть');
                        $('icon').addClass('icon-close').removeClass('icon-open');
                    },
                    open : function() {
                        $('calculator').addClass('hide');
                        $('calculator_link_a').set('html','Валютный калькулятор');
                        $('icon').removeClass('icon-close').addClass('icon-open');
                    }
                }
            },
            toggle_at_init : true
        });

    });
    
</script>
    </div>

    


    

    

    

    
    
    <!--    .BEGIN Help    -->
    
    
    <!-- Отзывы по модели -->
    
    
    <!-- if expr="$final_new_auto = 1" -->
    
    
    
    
    <!--    .END Help    -->
    

    

    
        <div style="text-align: center; margin-bottom: 10px;" id="search_banner_300x100_1"></div>
    

    
        <!--    .BEGIN Market    -->
        <div class="box-panel">

            <div class="head">
                <i class="icon-head-market"></i>
                    Автотовары
                <span class="area">
                    <a href="http://market.auto.ria.ua?utm_source=autoria&utm_medium=center_block&utm_campaign=markettovar" target="_blank">
                              Смотреть все
                             </a>
                    <i class="icon-view"></i>
                </span>
            </div>

            <div class="panel right-catalog-market">
                
                
                        
        <!--    .BEGIN one item catalog    -->
             
            <div class="item">

                <a class="photo" href="http://market.auto.ria.ua/shina-toyo-87393.html?utm_source=autoria&utm_medium=right_block&utm_campaign=markettovar">
                    <img src="http://img.ria.ua/photos/auto/treba/3/384/38401/38401lx.jpg" class="photo-85x56">
                </a>
                <dl class="subscribe-item">
                    <dt class="title">
                        <a title="" href="http://market.auto.ria.ua/shina-toyo-87393.html?utm_source=autoria&utm_medium=right_block&utm_campaign=markettovar">
                            Toyo 350
                        </a>
                    </dt>
                    <dd class="rows">
                            
                                Шины
                            
                    </dd>
                    <dd class="rows price">
                        <strong class="green">416</strong> грн.
                    </dd>
                </dl>
                
            </div>
             
            <div class="item">

                <a class="photo" href="http://market.auto.ria.ua/antiradar-sho-me-86085.html?utm_source=autoria&utm_medium=right_block&utm_campaign=markettovar">
                    <img src="http://img.ria.ua/photos/auto/treba/24/2411/241129/241129lx.jpg" class="photo-85x56">
                </a>
                <dl class="subscribe-item">
                    <dt class="title">
                        <a title="" href="http://market.auto.ria.ua/antiradar-sho-me-86085.html?utm_source=autoria&utm_medium=right_block&utm_campaign=markettovar">
                            SHO-ME 685
                        </a>
                    </dt>
                    <dd class="rows">
                            
                                Антирадары
                            
                    </dd>
                    <dd class="rows price">
                        <strong class="green">784</strong> грн.
                    </dd>
                </dl>
                
            </div>
           
        <!--    .END one item catalog    -->
                
            </div>


        </div>
    <!--     .END Market    -->
    

    
    
     
        <div style="text-align: center; margin-bottom: 10px;" id="search_banner_300x100_2"></div>
        <div style="text-align: center; margin-bottom: 10px;" id="search_banner_test"></div>
    


    

    
        <!--    .BEGIN Social Networks    -->
<div class="box-panel">

    <div class="head" style="margin-bottom: 14px;">
        <i class="icon-head-feedback"></i>
        Мы в социальных сетях
    </div>


        <div id="vk_groups"></div>

        <div id="fb-root"></div>

       <div class="fb-like-box" data-href="http://www.facebook.com/AUTO.ria.ua" data-width="300" data-height="220" data-show-faces="true" data-stream="false" data-border-color="#ddd" data-header="true"></div>
      
       <div id="ok_group_widget"></div>
       
        <g:plus href="https://plus.google.com/110464453590594722256" width="300" height="69" ></g:plus>
        
        <div style="margin-top: 10px">
            <a href="https://twitter.com/AUTO_ria_ua" class="twitter-follow-button" data-show-count="true" data-lang="ru" data-size="large">Читать @AUTO_ria_ua</a>
        </div>
        
</div>
<!--    .END Social Networks    -->
    


     
        <!--    .BEGIN Club    -->
<div class="box-panel">
    <div class="head">
        <i class="icon-head-feedback"></i>
        <a href='/forum' class="club-ria-ua"></a>
    </div>
    <div class="panel">
        <strong class="size-15">Мы в социальных сетях:</strong>
        <div class="social-network">
            <a target="_blank" href="http://vkontakte.ru/auto_ria_ua" class="item-social" title="вконтакте" onclick="_gaq.push(['_trackEvent',  'Right_panel', 'Click_on_vk', location.href]);" >
                <i class="icon-social-vkontakte"></i>вконтакте
            </a>
            <a target="_blank" href="http://www.facebook.com/AUTO.ria.ua" class="item-social" title="Facebook"  onclick="_gaq.push(['_trackEvent',  'Right_panel', 'Click_on_fb', location.href]);" >
                <i class="icon-social-facebook"></i>Facebook
            </a>
            <a target="_blank" href="http://twitter.com/auto_ria_ua" class="item-social" title="Twitter"  onclick="_gaq.push(['_trackEvent',  'Right_panel', 'Click_on_tw', location.href]);" >
                <i class="icon-social-twitter"></i>Twitter
            </a>
            <a target="_blank" href="/pdd_online/" class="item-social" title="ПДД"  onclick="_gaq.push(['_trackEvent',  'Right_panel', 'Click_on_pdd', location.href]);" >
                <i class="icon-social-pddexam"></i>ПДД
            </a>
        </div>
       <dl class="unordered-list">
                <dt>
                    обсуждения Вконтакте:
                </dt>
                <dd>
                    <a href='/golink/?http://vk.com/topic-6499791_26585326' target="_blank" onclick="_gaq.push(['_trackEvent',  'Right_panel',  'Click_on_topic_Soveti', location.href]);">Советы по покупке, продаже и эксплуатации авто.</a>
                </dd>
                <dd>
                    <a href='/golink/?http://vk.com/topic-6499791_26504703' target="_blank" onclick="_gaq.push(['_trackEvent',  'Right_panel',  'Click_on_topic_Evronomera', location.href]);">Кто катается на европейских номерах по Украине??</a>
                </dd>
                <dd>
                    <a href='/golink/?http://vk.com/topic-6499791_26030111' target="_blank" onclick="_gaq.push(['_trackEvent',  'Right_panel', 'Click_on_topic_Poisk_zapchastey', location.href]);">Поиск/Продажа запчастей и аксессуаров к авто</a></dd>
                <dd>
                    <a href='/golink/?http://vk.com/topic-6499791_25948409' target="_blank" onclick="_gaq.push(['_trackEvent',  'Right_panel',  'Click_on_topic_IGRA', location.href]);">ИГРА: “Цепочка слов”</a></dd>
            </dl>
        <div class="view-all">
            <a href='/golink/?http://vk.com/board6499791' onclick="_gaq.push(['_trackEvent',  'Right_panel', 'Click_on_vk', location.href]);">Смотреть все</a>
            <i class="icon-view"></i>
        </div>
    </div>
</div>
<!--    .END Club    -->
        
        <!--    .BEGIN Partner Informer    -->
        <div class="box-panel rocon">
            <div class="panel partner-informer">
            <div id="newnet_block353"><a href="http://newsnet.in.ua/">Загрузка...</a></div>
<script type="text/javascript">
document.write("<sc"+"ript type='text/javascript' src='http://exchange.newsnet.in.ua/show.ad?inf=353&div=newnet_block353&ref="+escape(document.referrer)+"'></sc"+"ript>");
</script>
            </div>
        </div>
        <!--24tv.ua-->
        <div class="box-panel rocon">
            <div class="panel partner-informer">
                <div id='informer378'></div>
                <script type='text/javascript' src='http://24tv.ua/resources/informers/378_UTF8.js'></script>
              <!--div id='informerElection2012'></div>
             <script type='text/javascript' src='http://24tv.ua/resources/informers/election2012_UTF8.js'></script-->
            </div>
        </div>
        
       
         <!--drugasmuga 50% ICTV-->
        <div class="box-panel">
            <script src="http://fakty.ictv.ua/widgets/informers/informer.js?v1.9.14" type="text/javascript"/></script>
     <script type="text/javascript">
         var ictv_informer = "fakty_avtonews";
             get_ictvinformer (ictv_informer);
             </script>
        </div>
     
    <!--    .END Partner Informer    -->


     

   

    

    

    
        <div class="box-panel">
    <h3 class="head">
        <a href="javascript:void(0);">Продажа бу Toyota Auris  2008</a>
    </h3>
    <div class="panel about-us">
        
            Не важно, желаете вы <i>продать или купить автомобиль Toyota Auris 
                            2008 в Теребовле</i>, вы всегда можете использовать сайт AUTO.ria.ua в нужных целях.
            На данной странице вы видите <strong>авто объявление о продаже Toyota Auris  2008</strong>,
            где предоставляется вся необходимая информация об интересующей вас машине. Теперь только вы решаете, нужна вам эта модель Toyota, или нет.
        
    </div>
</div>

    <div>
        <div class="relink-panel">
            Предложения купить новый Ленд Ровер от автосалонов есть <a href="http://auto.ria.ua/newauto/car/landrover/">тут</a>, Посмотреть <a href="http://auto.ria.ua/newauto/car/ford/">новые Форд</a> от автосалонов Украины можно на автосайте AUTO.ria.ua, Жидкость для системы смазки, объявления <a href="http://zapchasti.ria.ua/oiling/jidkost-tormoznaya/">продам тормозную жидкость</a> на нашем сайте
        </div>
    </div>



    

    


    
        <div class="box-panel">
    <div class="boxed">
        <!-- ##PANEL_Partneri_sayta## -->
          <noindex>
            <div  style="float: left;">

                <!--LiveInternet counter--><script type="text/javascript"><!--
                new Image().src = "//counter.yadro.ru/hit;RIA?r"+
                escape(document.referrer)+((typeof(screen)=="undefined")?"":
                ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
                screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
                ";"+Math.random();//--></script><!--/LiveInternet-->


                <!--LiveInternet logo--><a href="http://www.liveinternet.ru/click"
                target="_blank"><img src="//counter.yadro.ru/logo?12.6"
                title="LiveInternet: показане число переглядів за 24 години, відвідувачів за 24 години й за сьогодні"
                alt="" border="0" width="88" height="31"/></a><!--/LiveInternet-->
                
            </div>
        </noindex>
        <!-- /##PANEL_Partneri_sayta## -->
    </div>
</div>

    

</div>
<!--    .END Right Panel    -->

                    
                <script>
                    var containers = {
                        '300x100_1' : '300x100_1_container',
                        '300x100_2' : '300x100_2_container',
                        '380x60' : '380x60_container',
                        '380x60_2' : '380x60_2_container',
                        '380x60_3' : '380x60_3_container',
                        '730x90' : '730x90_container',
                        'top_link' : 'top_link_container',
                        'test' : 'test_container'
                    }
                    var places = {
                        '300x100_1' : 'search_banner_300x100_1',
                        '300x100_2' : 'search_banner_300x100_2',
                        '380x60' : '380x60_place',
                        '380x60_2' : '380x60_2_place',
                        '380x60_3' : '380x60_3_place',
                        '730x90' : '730x90_place',
                        'top_link' : 'top_link_place',
                        'test' : 'search_banner_test'
                    };
                    Object.each(containers, function(item, index){
                        if ($(item) && $(places[index])) {
                            $(item).replaces($(places[index]));
                        }
                    });
                </script>  
                    

           