    <!--<div id="search_auto_results" class="standart-view"> -->
    <div id="search_auto_results" class="gallery-view">
        <input type="hidden" id="queryString" name="queryString" value="<?php echo $this->queryString; ?>">
        <input type="hidden" id="count_result" name="count_result" value="<?php echo $this->count_result; ?>">
        
           <form id="search_ajax_form" method="get">
                 <input type="hidden" id="count_per_page" name="count_per_page" value="<?php echo $this->query['count_per_page']; ?>">
               
                <input type="hidden" id="block_view" name="block_view" value="<?php echo $this->query['block_view']; ?>">
                <input type="hidden" id="search_sort" name="search_sort" value="<?php echo $this->query['search_sort']; ?>">                
               
                <input type="hidden" id="auto_id" name="auto_id" value="<?php echo $this->query['auto_id']; ?>">
                <input type="hidden" id="category_id" name="category_id" value="<?php echo $this->category_id; ?>">
                <input type="hidden" id="bodystyle" name="bodystyle" value="<?php echo $this->query['bodystyle']; ?>">
                <input type="hidden" id="mark" name="mark" value="<?php echo $this->query['mark']; ?>">
                <input type="hidden" id="model" name="model" value="<?php echo $this->query['model']; ?>">
                
                <?php if(!empty($this->query['region'])){ ?>
                    <input type="hidden" id="region" class="m_state" name="m_state[]"  city_id="0" value="<?php echo $this->query['region']; ?>">
                    <input class="m_city" type="hidden" name="m_city[]" state_id="<?php echo $this->query['region']; ?>" value="0">
                <?php } ?>
                
                <input type="hidden" id="year_start" name="year_start" value="<?php echo $this->query['year_start']; ?>">
                <input type="hidden" id="year_end" name="year_end" value="<?php echo $this->query['year_end']; ?>">
                
                <input type="hidden" id="price_start" name="price_start" value="<?php echo $this->query['price_start']; ?>">
                <input type="hidden" id="price_end" name="price_end" value="<?php echo $this->query['price_end']; ?>">
                <input type="hidden" id="currency" name="currency" value="<?php echo $this->query['currency']; ?>">
                
                <input type="hidden" id="with_photo" name="with_photo" value="<?php echo $this->query['with_photo']; ?>">
                <input type="hidden" id="with_video" name="with_video" value="<?php echo $this->query['with_video']; ?>">
                
                <input type="hidden" id="mileage_start" name="mileage_start" value="<?php echo $this->query['mileage_start']; ?>">
                <input type="hidden" id="mileage_end" name="mileage_end" value="<?php echo $this->query['mileage_end']; ?>">
                
                <input type="hidden" id="transmission_id" name="transmission_id" value="<?php echo $this->query['transmission_id']; ?>">
                
                <input type="hidden" id="volume_start" name="volume_start" value="<?php echo $this->query['volume_start']; ?>">
                <input type="hidden" id="volume_end" name="volume_end" value="<?php echo $this->query['volume_end']; ?>">
                
                <input type="hidden" id="fuel_id" name="fuel_id" value="<?php echo $this->query['fuel_id']; ?>">
                <input type="hidden" id="drive_id" name="drive_id" value="<?php echo $this->query['drive_id']; ?>">
                
                <input type="hidden" id="color_id" name="color_id" value="<?php echo $this->query['color_id']; ?>">
                
                <?php if(isset($this->query['m_state'])){
                        foreach($this->query['m_state'] as $k => $v){
                            echo '<input class="m_state" type="hidden" city_id="" name="m_state[]" value="' . $v . '">';
                        }
                      } ?>
             </form>
        
        
<?php foreach ($this->paginator as $car) { ?>
           <div class="item">
                <div class="ticket-gallery <?php if ($car->priority != 'none') {
        echo 'paid';
    } ?>" ticket_status_id="0" ticket_auto_id="6992649">
                    <div class="head-ticket">
                        <div class="action-bar">
                            <a class="item icon-chips" title="Фишек нет. Что это такое?" onclick="_gaq.push(['_trackEvent', 'Paid_Promote', 'Click_on_Button_Icon', 'Search_Result']); fishkiObj.getForm(6992649);" href="javascript:void(0);"> 0 </a>
                            <a class="item icon-star" content_type_id="1" item_id="6992649" pelement="auto_add_to_notepad" title="Добавить в блокнот" href="javascript:void(0);"></a>
                            <span class="item-check" title="Добавить к сравнению">
                                <input type="checkbox" item_id="6992649" content_type_id="1" auto_name="Toyota Land Cruiser Prado 60-th Anniversary" auto_id="6992649" pelement="auto_compare_checkbox">
                                <span class="tooltip succes larr __top hide" pelement="auto_compare_popup"> </span>
                            </span>
                            <?php if ($car->priority != 'none') { ?>
                                    <i class="label-<?php echo $car->priority; ?>" onclick="fishkiObj.getForm(10043883); return false;"></i>
                            <?php } ?>
                        </div>
                        <span class="city">
                            <a title="Поиск объявлений по региону <?php echo $car->city_name; ?>." href="city/<?php echo $car->city_name; ?>/"><?php echo $car->city_name; ?></a>
                            <a class="icon-up-ticket" title="Поднять вверх при поиске" target="_blank" onclick="fishkiObj.getForm(6992649); _gaq.push(['_trackEvent', 'Popup_Fishek', 'Strelka', 'Search_Oldcar']); return false;" href="/fishki-group/"></a>
                        </span>
                        <h3 class="head-car">
                            <a title="<?php echo $car->mark_name . ' ' . $car->model_name . ' ' . $car->year; ?>" nav_mem="6992649" href="/index/view/id/<?php echo $car->id; ?>"><?php echo $car->mark_name . ' ' . $car->model_name; ?></a>
                            <?php echo $car->year; ?>
                        </h3>
                    </div>
                    <a class=" photo photo-295x195 " title="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" href="/index/view/id/<?php echo $car->id; ?>">
                        <?php if ($car->image != null) { ?>
                                    <img src="/images/photos/<?php echo $car->id; ?>/<?php echo $car->image; ?>">
    <?php }                   else { ?>
                                    <?php if ($car->priority != 'none') { ?><img src="http://img.auto.ria.ua/images/languages/ru/no-photo/no-photo-295x195.jpg"><?php } else { ?><img src="http://img.auto.ria.ua/images/languages/ru/no-photo/no-photo-295x195.jpg"><?php } ?> 

                             <?php } ?>
                    </a>
                    <div class="definition-data">
                        <div class="price" currency_id="1">
                                <?php if ($car->currency == 'UAH') { ?>
                                    <span class="grey" title="UAH"><?php echo $car->price; ?> грн.</span>
                                    <span class="nbu">по курсу НБУ</span> $
                                    <strong class="green" title="USD"><?php echo intval($car->price / $this->er); ?></strong>
                                <?php } else if ($car->currency == 'USD') { ?>
                                    <span class="grey" title="UAH"><?php echo intval($car->price); ?> грн.</span>
                                    <span class="nbu">по курсу НБУ</span> $
                                    <strong class="green" title="USD"><?php echo intval($car->price / $this->er); ?></strong>
                                <?php } else if ($car->currency == 'EUR') { ?>
                                    <span class="grey" title="UAH"><?php echo intval($car->price); ?> грн.</span>
                                    <span class="nbu">по курсу НБУ</span> $
                                    <strong class="green" title="USD"><?php echo intval($car->price / $this->er); ?></strong>
                                <?php } ?>
                        </div>
                        <ul class="characteristic">
                                <li class="item-char" title="Тип топлива">
                                    <?php if (!empty($car->fuel_type) || !empty($car->volume)) { ?>
                                        <i class="icon-char-fuel"></i>
                                        <?php echo $car->fuel_type; ?>, <?php echo number_format($car->volume, 2, '.', ''); ?> л.
                                    <?php } else { ?>
                                        <i class="icon-fuel"></i>
                                        Не указано
                                    <?php } ?>
                                </li>
                                <li class="item-char" title="Пробег">

                                    <?php if (!empty($car->mileage)) { ?>
                                        <i class="icon-char-mileage"></i>
                                        <?php echo $car->mileage; ?> тыс.км.
                                    <?php } else { ?>
                                        <i class="icon-mileage"></i>
                                        Не указано
                                    <?php } ?>
                                </li>
                                <li class="item-char" title="Тип коробки передач">
                                    <?php if (!empty($car->trans_type)) { ?>
                                        <i class="icon-char-transmission"></i>
                                        <?php echo $car->trans_type; ?>
                                    <?php } else { ?>
                                        <i class="icon-transmission"></i>
                                        Не указано
                                    <?php } ?>
                                </li>
                                <li class="item-char" title="Цвет кузова">

                                    <?php if (!empty($car->color)) { ?>
                                        <i class="icon-char-color"></i>
                                        <?php echo $car->color; ?>
                                    <?php } else { ?>
                                        <i class="icon-color"></i>
                                        Не указано
                                    <?php } ?>
                                </li>
                            </ul>
                    </div>
                    <div class="footer-ticket">
                        <span class="view-all">
                            <a nav_mem="6992649" href="/index/view/id/<?php echo $car->id; ?>">Подробно</a>
                            <i class="icon-view"></i>
                        </span>
                        <div class="charlist-data">
                            <span class="date-add" title="Объявление добавлено 15.08.2013" pvalue="17:00:37 15.08.2013" pelement="date_add">
                                
                                <?php echo Base_ElapsedTime::getAddCarTime(strtotime($car->added)); ?>
                            </span>
                            <?php if (isset($this->photos_cnt[$car->id])) { ?>
                                <i class="icon-photo-red" title="<?php echo $this->photos_cnt[$car->id]; ?> фотографий"></i><?php echo $this->photos_cnt[$car->id]; ?>
                            <?php } else { ?>
                                <i class="icon-photo-grey" title="Нет фото"></i>
                            <?php } ?>
                                                        
                            <i class="icon-video-red" title="1 видеороликов"></i> 1
                            <?php if (isset($car->exchange) && $car->exchange == '1') { ?>
                                <i class="icon-char-exchange" title="Возможен обмен"></i>
                                <span class="title-char">Обмен</span>
                            <?php } ?>
                            <?php if (isset($car->auction) && $car->auction == '1') { ?>
                                <i class="icon-char-auction"></i>
                                <span class="title-char" title="Торги">Торги</span>
                            <?php } ?>
                                                        
                        </div>
                    </div>
                </div>
            </div>
<?php } ?>
<?php //foreach($this->regions as $region){  ?>
<?php //echo $region->name;  ?>
<?php //} ?>
    </div>



    <div style="text-align: center; margin-bottom: 10px;" id="search_result_banner_after_3" class="hide">

    </div>
    <div class="window-fixed hide" id="houses_popup"></div>




    <!--    .BEGIN Pager    -->
    <div style="display: none;">
        <!--<div>-->
        <hr noshade="noshade">
        /blocks_search/pagination/search/?catalog_name=search&person_id=0
        <hr noshade="noshade">
    </div>
    <!--    .BEGIN Pager    -->
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/my_paginator.phtml', array('queryString' => $this->queryString));
?>