<div class="row content-main">
    <div class="left-panel span3">
        <dl class="user-menu">
            <!-- SSI: Блок Мой Автосалон -->
            <dt class="title">
            <i class="icon-menu-add"></i>
            <a href="add_auto.html" title="Добавить объявление" >
                Добавить объявление
            </a>
            </dt>
            <dt class="title">
            <i class="icon-menu-offer"></i>
            Мои объявления
            </dt>
            <dd class="item-menu">
                <a class="subhead" href="user/menu/allCars/" >Автомобили</a>
                <ul class="sublist">
                    <li class="subitem">
                        <?php if (count($this->published)) { ?>
                            <a href="user/menu/?section=active&viewType=active" >Опубликованные</a>&nbsp;<em><?php echo count($this->published); ?></em>
                        <?php } ?>
                    </li>

                    <li class="subitem">
                        <?php if (count($this->archived)) { ?>
                            <a href="user/menu/?section=archive&viewType=all">Архив</a>&nbsp;<em><?php echo count($this->archived); ?></em>
                        <?php } ?>
                    </li>

                    <li class="subitem">
                        <a href="?target=search&event=little&category=0&user_id=2287191">Все объявления с моим телефоном</a>&nbsp;<em>1</em>
                    </li>
                </ul>
            </dd>
            <dd class="item-menu">
                <a class="subhead" target="_blank" href="http://www.ria.ua/user" >Мои запчасти</a>
            </dd>
            <dt class="title">
            <i class="icon-menu-notifi"></i>
            <a href="mynotifications/" >Уведомления</a>
            </dt>
            <dd class="item-menu">
                <a href="mynotifications/?&sort_by=important" title="" >Важные</a>&nbsp;<em>1</em>
            </dd>
            <dd class="item-menu">
                <a href="mynotifications/?&sort_by=informative" title="" >Информирующие</a>&nbsp;<em>5</em>
            </dd>
            <dt class="title">
            <i class="icon-menu-commerc"></i>
            <a href="myservice/" >Коммерческие сервисы</a>
            </dt>
            <dd class="item-menu">
                <a  href="myservice/" title="Важная информация" >Важная информация</a>
            </dd>
            <dd class="item-menu">
                <a href="/stolzakazov/zapchasti/" title="Стол заказов запчастей" onclick="_gaq.push(['_trackEvent', 'Stol_Zakazov_Zapch', 'Click_on_Aplication_StZZ', 'My_Menu']);">Стол заказов запчастей</a>
            </dd>
            <dd class="item-menu">
                <a href="autoseller/info/" title="Моя Автопродажа" onclick="//_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Autoseller', 'Myservice']);">Моя Автопродажа</a>&nbsp;<em>3</em>
            </dd>
            <dd class="item-menu">
                <a href="fishki-group/" title="Управление объявлениями" >Управление объявлениями</a>
            </dd>
            <dd class="item-menu">
                <a class="new" href="fishki-optom/" title="Фишки оптом" >Фишки оптом</a>
            </dd>
            <dd class="item-menu">
                <a class="new" href="top-optom/" title="ТОП оптом" >ТОП оптом</a>
            </dd>
            <dt class="title">
            <i class="icon-menu-subscribe"></i>
            <a href="/subscribe/" title="Рассылка" >Рассылка</a>
            </dt>
            <dd class="item-menu">
                <a title="Мои профили рассылки" href="/subscribe/" >Мои профили рассылки</a>
            </dd>
            <dd class="item-menu">
                <a title="Создать профиль" href="/subscribe/?add_profile=1" >Создать профиль</a>
            </dd>
            <dd class="item-menu">
                <a href="/deskoffers/profiles" title="Подписка на Стол заказов" onclick="_gaq.push(['_trackEvent', 'Stol_Zakazov_Zapch', 'Click_on_Subscriptions_StZZ', 'My_Menu']);">Стол заказов</a>
            </dd>
            <dt class="title">
            <i class="icon-menu-subscribe"></i>
            <a href="/avtoprovereno/" title="Авто проверено" >Авто проверено</a>
            </dt>

            <dt class="title">
            <i class="icon-menu-profile"></i>
            Мои данные
            </dt>
            <dd class="item-menu">
                <a title="Моя анкета" href="/my_profile/edit/" >Моя анкета</a>
            </dd>
            <dd class="item-menu">
                <a title='Мой "Черный список"' href="user/blacklist" >Мой "Черный список"</a>
            </dd>

            <dd class="item-menu">
                <a href="user/change_password.html" title="Поменять пароль" >Поменять пароль</a>
            </dd>
            <dd class="item-menu">
                <a title="Выход" href="?exit=yes" >Выход</a>
            </dd>
            <dt class="title">
            <i class="icon-menu-app"></i>
            Мобильное приложение
            </dt>
            <dd class="item-menu">
                <a href="https://play.google.com/store/apps/details?id=ria.ua" target="_blank" >Для Android</a>
            </dd>
            <dd class="item-menu">
                <a href="http://itunes.apple.com/ru/app/ria.ua/id508748317?l=ru&ls=1&mt=8" target="_blank" >Для iPhone</a>
            </dd>
        </dl><!-- Page load array script time : 0.10322999954224
        -->
        <div class="box-panel">
            <div class="head">
                <i class="icon-head-help"></i> <a href="/help/" title="Помощь">Помощь</a>
            </div>
            <!-- include virtual="/pseudo_services/help_units/person_manager/?user_id=2287191&lang_id=2" -->



            <div class="support" id="support_manager_block">
                <img height="90" width="67" alt="Олейник Надежда" src="http://img.auto.ria.ua/images/demo/Nadia_Oleynik.png" class="photo">

                <div class="contact-data">
                    <div class="title">
                        Олейник Надежда
                    </div>
                    <p class="desc grey">Консультации по вопросам работы сайта AUTO.ria.ua</p>

                    <div class="list-phone">
                        <p class="phone"><i class="icon-phone"></i>(067) 431-82-29</p>
                        <p class="phone hide"><i class="icon-phone"></i>0-800-21-00-12</p>
                        <p class="phone hide"><i class="icon-phone"></i>(0432) 555-213</p>
                        <p class="phone hide"><i class="icon-phone"></i>(0432) 555-200</p>
                        <p class="phone hide"><i class="icon-phone"></i>(093) 190-27-23</p>
                        <p class="phone hide"><i class="icon-phone"></i>(050) 416-86-88</p>
                        <a href="javascript:void(0);" onclick="$$('div.list-phone p.phone').removeClass('hide');
                        this.addClass('hide');">
                            Показать все телефоны<i class="icon-open"></i>
                        </a>

                    </div>
                </div>

                <p class="characteristic">
                    <span class="item-param">
                        <i class="icon-id-item"></i>Ваш клиентский номер:
                        <span class="inline allotted">2287191</span>
                        <a target="_blank" href=" http://help.ria.ua/index.php?/Knowledgebase/Article/View/411/0/chto-tkoe-klientskijj-nomer" title=""><img width="14" height="14" src="http://img.auto.ria.ua/images/demo/ico-help.gif" style=" margin-bottom: -2px;"></a>
                    </span>
                </p>

                <p>
                    <i class="icon-help"></i>
                    <a href="/question/my_active_ads/">Обратиться в службу поддержки</a>
                </p>
                <!--Доменная зона: ua -->

                <p>
                    <i class="icon-bezpeka"></i>
                    <a href="http://bezpeka.ria.ua/">Узнать о безопасности сделок от RIA</a>
                </p>

            </div>

        </div>
    </div>
    <div class="main-panel span9">
        <div class="head-box line-grove" style="margin-bottom: 20px">
            Мои автомобили        </div>
        <div class="about-section">
            <p>Мои автомобили - это раздел, предназначенный для оперативного управления Вашими объявлениями на сайте. С его помощью Вы можете легко и удобно отслеживать статистику Ваших объявлений: их тип, дату публикации, статистику просмотров, качество наполнения и позицию в поиске. В разделе представлены основные инструменты управления объявлениями: поднятие в результатах поиска, обновление даты публикации, перемещение в архив, редактирование и удаление.</p>        </div>
        <div class="info icons">
            Поднимайте свое объявление в результатах поиска и привлекайте больше покупателей. Узнайте <a href="/?target=view&amp;event=promo" >как сделать своё объявление на сайте популярным и привлекательным</a>.        </div>

        <?php if (count($this->published)) { ?>
            <section id="user_menu__container_active_active" class="box-panel">
                <div class="head-box"> Опубликованные </div>
                <div id="user_menu__main_table_active_active" class="table-myauto">
                    <?php foreach ($this->published as $car) { ?>
                    <div class="item-ticket" auto_ticket="<?php echo $car->id; ?>">
                            <label class="check-item" for="check_auto_11871440">
                                <input id="check_auto_11871440" class="check" type="checkbox" value="11871440" name="check_auto[11871440]">
                            </label>
                            <div class="content-myauto">
                                <div class="content">
                                    <?php if ($car->image != null) { ?>
                                        <a class="photo" target="_blank" href="/index/view/id/<?php echo $car->id; ?>" nav_mem="11871440">
                                            <img width="135" alt="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" title="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" nav_mem="11871440" src="/images/photos/<?php echo $car->id; ?>/<?php echo $car->image; ?>">
                                        </a>
                                    <?php } else { ?>
                                        <a class="photo" target="_blank" href="/catalog/add/step/addphoto/autoId/<?php echo $car->id; ?>" nav_mem="11871440">
                                            <img width="135" alt="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" title="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" nav_mem="11871440" src=" http://img.auto.ria.ua/images/languages/ru/no-photo/add-photo-135x90.jpg ">
                                        </a>

                                    <?php } ?>

                                    <div class="content-item">
                                        <h3 class="head-item">
                                            <a title="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" nav_mem="11871440" href="/index/view/id/<?php echo $car->id; ?>"><?php echo $car->mark_name . ' ' . $car->model_name; ?></a>
                                            &nbsp;<?php echo $car->year; ?>
                                        </h3>
                                        <p class="city"><?php echo $car->city_name; ?></p>
                                        <div class="corect-price">
                                            <?php if ($car->currency == 'UAH') { ?>
                                                <span title="UAH">грн.</span>
                                                <span class="price"><?php echo $car->price; ?> грн.</span>
                                            <?php } else if ($car->currency == 'USD') { ?>
                                                <span title="USD">$</span>
                                                <span class="price"><?php echo intval($car->price / $this->usd); ?></span>
                                            <?php } else if ($car->currency == 'EUR') { ?>
                                                <span title="EUR">€</span>
                                                <span class="price"><?php echo intval($car->price / $this->eur); ?></span>
                                            <?php } ?>
                                        </div>
                                        <p class="position" style="">
                                            <a href="/?target=search&event=little&marka=98&model=30098&scroll_to_auto_id=11871440&page=0" position_in_search="11871440" title="Показать на странице поиска" target="_blank" style="text-decoration: none; color: black; font-weight: bold;">№1</a>
                                            в поиске
                                        </p>
                                    </div>
                                    <div class="media-data">
                                        <span class="item" title="Количество фото">
                                            <i class="icon-photo"></i>
                                            <?php if (isset($this->photos_cnt[$car->id])) { ?>
                                                <a title="Нажмите, чтоб добавить фото" style="text-decoration: none; color: black; font-weight: bold;" href="/catalog/add/step/addphoto/autoId/<?php echo $car->id; ?>" target="_blank"><?php echo $this->photos_cnt[$car->id]; ?></a>
                                            <?php } else { ?>
                                                <a title="Нажмите, чтоб добавить фото" style="text-decoration: none; color: black; font-weight: bold;" href="/catalog/add/step/addphoto/autoId/<?php echo $car->id; ?>" target="_blank">Нет фото</a>
                                            <?php } ?>
                                        </span>
                                        <span class="item" publication_statistic="publication_statistic" style="">
                                            <i class="icon-through"></i>
                                            <a target="_blank" href="/auto_statistic/11871440/">Статистика объявления</a>
                                        </span>
                                        <span class="tinycomment" onclick="window.open('/auto_acura_el_11871440.html#final_page__comments_container', '_blank');" style="display: none;" comments_count="11871440" title="Нажмите, чтоб перейти к комментариям">загрузка...</span>
                                    </div>
                                </div>
                                <div class="current-state">
                                    <p class="item-state">
                                        <i class="icon-type"></i>
                                        <span title="Обычное объявление" auto_id="11871440" action="raise_up"> Обычное </span>
                                    </p>
                                    <p class="item-state">
                                        <i class="icon-time-grey"></i>
                                        <strong class="gray" format_date="<?php echo $car->added; ?>" processed="true"><?php echo date('d.m.Y', strtotime($car->added)); ?></strong>
                                    </p>
                                    <p class="item-state">
                                        <i class="icon-auto-dibs"></i>
                                        фишек:
                                        <strong title="Нажмите, чтоб добавить фишек" style="cursor: pointer;" auto_id="11871440" action="raise_up">0</strong>
                                    </p>
                                    <p class="item-state" style="display: none;">
                                        <i class="icon-mail"></i>
                                        <span title="Сообщения, которые были отправлены вам по электронной почте" mail_count="11871440">загрузка...</span>
                                        <span mail_count_word="11871440">сообщение</span>
                                    </p>
                                </div>
                                <div class="current-state">
                                    <p class="item-state">
                                        <i class="icon-views"></i>
                                        <span title="Количество просмотров объявления" view_count="11871440">21</span>
                                    </p>
                                    <p class="item-state" title="Дата окончания публикации 23.09.2013">
                                        <i class="icon-time-grey"></i>
                                        до
                                        <strong class="gray" may_be_in_the_future="" format_date="2013-09-23 16:33:34" processed="true">23.09.2013</strong>
                                    </p>
                                    <p class="item-state" title="ID объявления" ticket_id="">
                                        <i class="icon-id-item"></i>
                                        <?php echo $car->id; ?>
                                    </p>
                                    <div class="item-republication" automatic_republication_container="11871440" style="" title="Размещение объявления на сайте не будет продлеваться автоматически.По окончанию срока публикации оно переместится в Архив.">
                                        <i class="icon-republication-off" automatic_republication_icon="11871440"></i>
                                        Повторная публикация
                                        <a class="red" automatic_republication_status="11871440" expired_date="23.09.2013">выключена</a>
                                    </div>
                                </div>
                                <ol class="control-list">
                                    <li>
                                        <a onclick="_gaq.push(['_trackEvent', 'Paid_Promote', 'Click_on_Button_Up', 'Search_Result']);" title="Поднять объявление в поиске, опубликовав его как "Срочное" или "Выделенное"" action="raise_up" auto_id="11871440" href="javascript:void(0);">
                                            <i class="icon-up-blue"></i>
                                            Поднять
                                        </a>
                                    </li>
                                    <li>
                                        <a title="Обновление даты и продление срока публикации объявления" onclick="_gaq.push(['_trackEvent', 'Paid_Promote', 'Click_on_Button_Re-Published', 'Search_Result']);" href="/addauto/republication/autoId/11871440/">Переопубликовать</a>
                                    </li>
                                    <li>
                                        <a title="Перейти к редактированию объявления" href="/catalog/add/step/autoinfo/autoId/<?php echo $car->id; ?>">Редактировать</a>
                                    </li>
                                    <li>
                                        <a action="inform_us_about_sale" auto_id="11871440" title="Сообщить о продаже" href="javascript:void(0);">Сообщить о продаже</a>
                                    </li>
                                    <li>
                                        <a class="to_archive" rel="<?php echo $car->id; ?>" href="javascript:void(0);">Удалить в архив</a>
                                    </li>
                                </ol>

                                <div id="autoDeleteReason<?php echo $car->id; ?>" class="pop-up-element" style="position: absolute; margin-top: 0; z-index: 1000; width: 350px; display: none; left: 352px; top: 98px;">
                                    <div class="left-shadow">
                                        <div class="right-shadow">
                                            <em class="tl-shadow"> </em>
                                            <em class="tr-shadow"> </em>
                                            <em class="bl-shadow"> </em>
                                            <em class="br-shadow"> </em>
                                            <a rel="<?php echo $car->id; ?>" class="close-alert" href="javascript:void(0);" name="closeAlert"> </a>
                                            <div class="top-shadow">
                                                <div class="bottom-shadow">
                                                    <div class="container-item">
                                                        <div id="reason-title-<?php echo $car->id; ?>" class="title text-l">Удаление объявления</div>
                                                        <div id="complaintAdvertisementResponseAjax-<?php echo $car->id; ?>" class="hide"> </div>
                                                        <div id="saled-form-<?php echo $car->id; ?>" saled="0">
                                                            <form id="complaintAdvertisementForm-<?php echo $car->id; ?>" class="grid-form" method="post" action="/user/myautos">
                                                                <div class="hidden">
                                                                    <input type="hidden" name="target" value="user">
                                                                    <input type="hidden" name="event" value="myauto">
                                                                    <input type="hidden" name="delete_id" value="<?php echo $car->id; ?>">
                                                                </div>
                                                                <p id="reason-reason-<?php echo $car->id; ?>">
                                                                    Пожалуйста, укажите причину, по которой Вы удаляете объявление
                                                                    <strong>
                                                                        <?php echo $car->mark_name . ' ' . $car->model_name . ' ' . $car->year; ?>г.в.
                                                                        <strong>:</strong>
                                                                    </strong>
                                                                </p>
                                                                <p class="box-check">
                                                                    <input auto_id="<?php echo $car->id; ?>" id="reason_id4-<?php echo $car->id; ?>" type="radio" name="reason_id" value="4">
                                                                    <label for="reason_id4-<?php echo $car->id; ?>">Авто продано с помощью AUTO.ria.ua</label>
                                                                </p>
                                                                <p class="box-check">
                                                                    <input auto_id="<?php echo $car->id; ?>" id="reason_id5-<?php echo $car->id; ?>" type="radio" name="reason_id" value="5">
                                                                    <label for="reason_id5-<?php echo $car->id; ?>">Авто продано в другом месте</label>
                                                                </p>
                                                                <p id="repub-11543114" class="box-check">
                                                                    <input auto_id="<?php echo $car->id; ?>" id="reason_id6-<?php echo $car->id; ?>" type="radio" name="reason_id" value="6">
                                                                    <label for="reason_id6-<?php echo $car->id; ?>">Я хочу разместить объявление заново</label>
                                                                </p>
                                                                <p id="changed-11543114" class="box-check">
                                                                    <input auto_id="<?php echo $car->id; ?>" id="reason_id7-<?php echo $car->id; ?>" type="radio" name="reason_id" value="7">
                                                                    <label for="reason_id7-<?php echo $car->id; ?>">Я передумал продавать автомобиль</label>
                                                                </p>
                                                                <div class="boxed box-button" style="margin: 10px">
                                                                    <span id="formmm_span_<?php echo $car->id; ?>" style="padding: 0;" class="button grey-30 disabled">
                                                                        <input class="to_archive_submit" auto_id="<?php echo $car->id; ?>" id="formmm_<?php echo $car->id; ?>" type="submit" disabled="disabled" onclick="//return confirm('Вы уверены, что хотите удалить объявление?');" value="Удалить">
                                                                    </span>
                                                                    <span style="padding: 0;"  class="button grey-30">
                                                                        <input class="to_archive_button_cancel" auto_id="<?php echo $car->id; ?>" type="button" value="Отмена">
                                                                    </span>
                                                                </div>
                                                            </form>
                                                        </div>
                                                        <div id="succes-remove-11543114" style="display: none">
                                                            <div class="succes-remove-ads" style="border: medium none; margin: 0 0 0 -20px; padding: 5px 15px 0 110px;">
                                                                <p class="box-check">
                                                                    Ваше объявление отмечено как
                                                                    <span class="bold size-14">"продано"</span>
                                                                </p>
                                                                <p class="box-check">Изменения вступят в силу в течении нескольких минут.</p>
                                                            </div>
                                                            <p class="box-check bold">
                                                                Спасибо, что воспользовались
                                                                <span style="color: #D0412E">AUTO.ria.ua!</span>
                                                            </p>
                                                            <div class="boxed box-button" style="margin: 0 0 0 115px;">
                                                                <span class="button grey-30">
                                                                    <input type="button" value="Закрыть" onclick="fToggle(11543114)">
                                                                </span>
                                                            </div>
                                                        </div>
                                                        <noindex>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    <?php } ?>
                </div>
            </section>
        <?php } ?>
        <section id="user_menu__container_archive_all" class="box-panel">
            <div class="head-box"> Архив </div>
            <div id="user_menu__main_table_archive_all" class="table-myauto">
                <?php foreach ($this->archived as $car) { ?>
                    <div class="item-ticket" auto_ticket="<?php echo $car->id; ?>">
                        <label class="check-item" for="check_auto_11871440">
                            <input id="check_auto_11871440" class="check" type="checkbox" value="11871440" name="check_auto[11871440]">
                        </label>
                        <div class="content-myauto">
                            <div class="content">
                                <?php if ($car->image != null) { ?>
                                    <a class="photo" target="_blank" href="/index/view/id/<?php echo $car->id; ?>" nav_mem="11871440">
                                        <img width="135" alt="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" title="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" nav_mem="11871440" src="/images/photos/<?php echo $car->id; ?>/<?php echo $car->image; ?>">
                                    </a>
                                <?php } else { ?>
                                    <a class="photo" target="_blank" href="/catalog/add/step/addphoto/autoId/<?php echo $car->id; ?>" nav_mem="11871440">
                                        <img width="135" alt="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" title="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" nav_mem="11871440" src=" http://img.auto.ria.ua/images/languages/ru/no-photo/add-photo-135x90.jpg ">
                                    </a>

                                <?php } ?>

                                <div class="content-item">
                                    <h3 class="head-item">
                                        <a title="<?php echo $car->mark_name . ' ' . $car->model_name; ?>" nav_mem="11871440" href="/index/view/id/<?php echo $car->id; ?>"><?php echo $car->mark_name . ' ' . $car->model_name; ?></a>
                                        &nbsp;<?php echo $car->year; ?>
                                    </h3>
                                    <p class="city"><?php echo $car->city_name; ?></p>
                                    <div class="corect-price">
                                        <?php if ($car->currency == 'UAH') { ?>
                                            <span title="UAH">грн.</span>
                                            <span class="price"><?php echo $car->price; ?> грн.</span>
                                        <?php } else if ($car->currency == 'USD') { ?>
                                            <span title="USD">$</span>
                                            <span class="price"><?php echo intval($car->price / $this->usd); ?></span>
                                        <?php } else if ($car->currency == 'EUR') { ?>
                                            <span title="EUR">€</span>
                                            <span class="price"><?php echo intval($car->price / $this->eur); ?></span>
                                        <?php } ?>
                                    </div>
                                    <p class="position" style="">
                                        <a href="/?target=search&event=little&marka=98&model=30098&scroll_to_auto_id=11871440&page=0" position_in_search="11871440" title="Показать на странице поиска" target="_blank" style="text-decoration: none; color: black; font-weight: bold;">№1</a>
                                        в поиске
                                    </p>
                                </div>
                                <div class="media-data">
                                    <span class="item" title="Количество фото">
                                        <i class="icon-photo"></i>
                                        <?php if (isset($this->photos_cnt[$car->id])) { ?>
                                            <a title="Нажмите, чтоб добавить фото" style="text-decoration: none; color: black; font-weight: bold;" href="/catalog/add/step/addphoto/autoId/<?php echo $car->id; ?>" target="_blank"><?php echo $this->photos_cnt[$car->id]; ?></a>
                                        <?php } else { ?>
                                            <a title="Нажмите, чтоб добавить фото" style="text-decoration: none; color: black; font-weight: bold;" href="/catalog/add/step/addphoto/autoId/<?php echo $car->id; ?>" target="_blank">Нет фото</a>
                                        <?php } ?>
                                    </span>
                                    <span class="item" publication_statistic="publication_statistic" style="">
                                        <i class="icon-through"></i>
                                        <a target="_blank" href="/auto_statistic/11871440/">Статистика объявления</a>
                                    </span>
                                    <span class="tinycomment" onclick="window.open('/auto_acura_el_11871440.html#final_page__comments_container', '_blank');" style="display: none;" comments_count="11871440" title="Нажмите, чтоб перейти к комментариям">загрузка...</span>
                                </div>
                            </div>
                            <div class="current-state">
                                <p class="item-state">
                                    <i class="icon-type"></i>
                                    <span title="Не опубликовано" auto_id="11871440" action="raise_up">Не опубликовано </span>
                                </p>
                                <p class="item-state">
                                    <i class="icon-time-grey"></i>
                                    <strong class="gray" format_date="<?php echo $car->added; ?>" processed="true"><?php echo date('d.m.Y', strtotime($car->added)); ?></strong>
                                </p>
                                <p class="item-state">
                                    <i class="icon-auto-dibs"></i>
                                    фишек:
                                    <strong title="Нажмите, чтоб добавить фишек" style="cursor: pointer;" auto_id="11871440" action="raise_up">0</strong>
                                </p>
                                <p class="item-state" style="display: none;">
                                    <i class="icon-mail"></i>
                                    <span title="Сообщения, которые были отправлены вам по электронной почте" mail_count="11871440">загрузка...</span>
                                    <span mail_count_word="11871440">сообщение</span>
                                </p>
                            </div>
                            <div class="current-state">
                                <p class="item-state" title="ID объявления" ticket_id="">
                                    <i class="icon-id-item"></i>
                                    <?php echo $car->id; ?>
                                </p>
                            </div>
                            <ol class="control-list">
                                <li>
                                    <a title="Обновление даты и продление срока публикации объявления" onclick="_gaq.push(['_trackEvent', 'Paid_Promote', 'Click_on_Button_Re-Published', 'Search_Result']);" href="/addauto/republication/autoId/11871440/">Опубликовать</a>
                                </li>
                                <li>
                                    <a title="Перейти к редактированию объявления" href="/catalog/add/step/autoinfo/autoId/<?php echo $car->id; ?>">Редактировать</a>
                                </li>
                                <li>
                                    <a class="delete_auto" auto_id="<?php echo $car->id; ?>" href="javascript:void(0);">Удалить с сайта</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                <?php } ?>
            </div>

            <p class="show-all-ticket">
                <a class="button" target="_blank" href="/user/menu/?section=archive&viewType=all"> Смотреть все объявления (4) </a>
            </p>
        </section>

    </div>

</div>