<!--    .BEGIN Left Panel    -->

<div class="left-panel span3">

    <dl class="user-menu">
        <!-- SSI: Блок Мой Автосалон -->
        <dt class="title">
            <i class="icon-menu-add"></i>
                <a href="add_auto.html" title="Добавить объявление" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Add', 'Menu']);">
                    Добавить объявление
                </a>
        </dt>
        
        <dt class="title">
            <i class="icon-menu-offer"></i>
                Мои объявления
        </dt>
        
        <dd class="item-menu">
            <a class="subhead" href="?target=user&event=myauto&section=all&viewType=all" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_All', 'Cars']);">Автомобили</a>
            <ul class="sublist">
            </ul>
        </dd>
        
        <dd class="item-menu">
            <a class="subhead" target="_blank" href="http://www.ria.ua/user" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_My_Zapchast', 'Ria']);">Мои запчасти</a>
        </dd>
        
        <dt class="title">
            <i class="icon-menu-notifi"></i>
            <a href="mynotifications/" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_All_Notifications', 'Notifications']);">Уведомления</a>
        </dt>
        
        <dt class="title">
            <i class="icon-menu-commerc"></i>
            <a href="myservice/" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_My_Service', 'Myservice']);">Коммерческие сервисы</a>
        </dt>
        
        <dd class="item-menu">
            <a  href="myservice/" title="Важная информация" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Important_Information', 'Myservice']);">Важная информация</a>
        </dd>
        
        <dd class="item-menu">
            <a href="/stolzakazov/zapchasti/" title="Стол заказов запчастей" onclick="_gaq.push(['_trackEvent', 'Stol_Zakazov_Zapch', 'Click_on_Aplication_StZZ', 'My_Menu']);">Стол заказов запчастей</a>
        </dd>
        
        <dd class="item-menu">
            <a href="autoseller/info/" title="Моя Автопродажа" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Autoseller', 'Myservice']);">Моя Автопродажа</a>&nbsp;<em>3</em>
        </dd>
        
        <dd class="item-menu">
            <a href="fishki-group/" title="Управление объявлениями" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Fishki', 'Myservice']);">Управление объявлениями</a>
        </dd>
        
        <dd class="item-menu">
            <a class="new" href="fishki-optom/" title="Фишки оптом" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Fishki_Optom', 'Myservice']);">Фишки оптом</a>
        </dd>
        
        <dd class="item-menu">
            <a class="new" href="top-optom/" title="ТОП оптом" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Top_Optom', 'Myservice']);">ТОП оптом</a>
        </dd>
        
        <dt class="title">
            <i class="icon-menu-subscribe"></i>
            <a href="subscribe" title="Рассылка" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Subscribe', 'Subscribe']);">Рассылка</a>
        </dt>
        
        <dd class="item-menu">
            <a title="Мои профили рассылки" href="subscribe?showProfiles=1" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Show_Profiles', 'Subscribe']);">Мои профили рассылки</a>
        </dd>
        
        <dd class="item-menu">
            <a title="Создать профиль" href="subscribe?create_profile=1" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Create_Profiles', 'Subscribe']);">Создать профиль</a>
        </dd>
        <dd class="item-menu">
            <a href="/deskoffers/profiles" title="Подписка на Стол заказов" onclick="_gaq.push(['_trackEvent', 'Stol_Zakazov_Zapch', 'Click_on_Subscriptions_StZZ', 'My_Menu']);">Стол заказов</a>
        </dd>
        
        <dt class="title">
            <i class="icon-menu-subscribe"></i>
            <a href="/avtoprovereno/" title="Авто проверено" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Provereno', 'Auto_Provereno'])">Авто проверено</a>
        </dt>
        
        <dd class="item-menu">
            <a title="Заказы без оплаты" href="/avtoprovereno/" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Without_Payments', 'Auto_Provereno'])">Заказы без оплаты</a>
        </dd>
        
        <dd class="item-menu">
            <a title="Заказы в работе" href="/avtoprovereno/" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_V_Rabote', 'Auto_Provereno'])">Заказы в работе</a>
        </dd>
        
        <dd class="item-menu">
            <a title="Заказы завершенные" href="/avtoprovereno/" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Zavershen', 'Auto_Provereno'])">Заказы завершенные</a>
        </dd>
        
        <dt class="title">
            <i class="icon-menu-profile"></i>
            Мои данные
        </dt>
        
        <dd class="item-menu">
            <a title="Моя анкета" href="?target=user&event=redug" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_My_Profile', 'My_Account'])">Моя анкета</a>
        </dd>
        
        <dd class="item-menu">
            <a title="Мои поиски" href="?target=user&amp;event=searchHistory" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Search_History', 'My_Account']);">Мои поиски</a>
        </dd>
        
        <dd class="item-menu">
            <a title='Мой "Черный список"' href="user/blacklist" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Blacklist', 'My_Account']);">Мой "Черный список"</a>
        </dd>

        <dd class="item-menu">
            <a href="user/change_password.html" title="Поменять пароль" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Change_Password', 'My_Account']);">Поменять пароль</a>
        </dd>
        
        <dd class="item-menu">
            <a title="Выход" href="?exit=yes" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Exit', 'Menu']);">Выход</a>
        </dd>
        
        <dt class="title">
            <i class="icon-menu-app"></i>
            Мобильное приложение
        </dt>
        
        <dd class="item-menu">
            <a href="https://play.google.com/store/apps/details?id=ria.ua" target="_blank" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Mobile_App_A', 'Promo']);">Для Android</a>
        </dd>
        
        <dd class="item-menu">
            <a href="http://itunes.apple.com/ru/app/ria.ua/id508748317?l=ru&ls=1&mt=8" target="_blank" onclick="_gaq.push(['_trackEvent', 'Menu_Target_User', 'Click_on_Link_Mobile_App_I', 'Promo']);">Для iPhone</a>
        </dd>
        
    </dl><!-- Page load array script time : 0.17323923110962
    -->                      


    <div class="box-panel">
        <div class="head">
            <i class="icon-head-help"></i> <a href="/help/" title="Помощь">Помощь</a>
        </div>

        <!--    (none) -->
        <!-- include virtual="/pseudo_services/help_units_right/person_manager/?user_id=3030847&direction=(none)" -->



        <div class="support" id="support_manager_block">
            <img height="90" width="67" alt="Олейник Надежда" src="http://img.auto.ria.ua/images/demo/Nadia_Oleynik.png" class="photo">

            <div class="contact-data" style="min-height: 80px;">
                <div class="title">
                    Олейник Надежда
                </div>
                <p class="desc grey">Консультации по вопросам работы сайта AUTO.ria.ua</p>

            </div>

            <div class="characteristic contact-data-seller">
                <div class="phone item-param">
                    <i class="icon-phone"></i>
                    <strong class="phone">(067) 469-04-10</strong>
                </div>
                <div class="phone item-param hide">
                    <i class="icon-phone"></i>
                    <strong class="phone">0-800-21-00-12</strong>
                </div>
                <div class="phone item-param hide">
                    <i class="icon-phone"></i>
                    <strong class="phone">(0432) 555-213</strong>
                </div>
                <div class="phone item-param hide">
                    <i class="icon-phone"></i>
                    <strong class="phone">(0432) 555-200</strong>
                </div>
                <div class="phone item-param hide">
                    <i class="icon-phone"></i>
                    <strong class="phone">(093) 561-61-61</strong>
                </div>
                <div class="phone item-param hide">
                    <i class="icon-phone"></i>
                    <strong class="phone">(050) 416-86-88</strong>
                </div>
                <p class="item-param">
                    <a href="javascript:void(0);" onclick="$$('div.characteristic div.phone').removeClass('hide');
                this.addClass('hide');">
                        Показать все телефоны
                    </a>
                </p>



                <p class="characteristic item-param">
                    <!--<span class="item-param">-->
                    <i class="icon-id-item"></i>Ваш клиентский номер: 
                    <span class="inline allotted">3030847</span>  
                    <a target="_blank" href=" http://help.ria.ua/index.php?/Knowledgebase/Article/View/411/0/chto-tkoe-klientskijj-nomer" title=""><img width="14" height="14" src="http://img.auto.ria.ua/images/demo/ico-help.gif" style=" margin-bottom: -2px;"></a>
                    <!--</span>-->
                </p>

                <p class="item-param" >
                    <i class="icon-help"></i>
                    <a href="/question/main/0">Обратиться в службу поддержки</a>
                </p>

                <p class="item-param" >
                    <i class="icon-bezpeka"></i>
                    <a href="http://bezpeka.ria.ua/">Узнать о безопасности сделок от RIA.ua</a>
                </p>

            </div>
        </div>





    </div>

    <noindex>
        <script type="text/javascript">

            $$("div#support_manager_block").addEvent('click', function(e) {
                var obj = e.target;
                var el_event = obj.get('el_event');
                switch (el_event) {
                    case "right_message":
                        if (this.getElement('div.mail div.popup').hasClass('hide'))
                            this.getElement('div.mail div.popup').removeClass('hide');
                        else
                            this.getElement('div.mail div.popup').addClass('hide');
                        break;
                    case "cancel" :
                    case  "close_message":
                        //                        this.getElements('div.mail div.popup form.grid-span1 input').set("value", "");
                        this.getElements('div.mail div.popup form.grid-span1 textarea').set("value", "");
                        this.getElement('div.mail div.popup').addClass('hide');
                        break;
                    case "send_message":
                        //                        this.getElements('div.mail div.popup form.grid-span1');

                        url = "/consultation/sendmessage/";
                        if (this.getElements('div.mail div.popup form.grid-span1 textarea')[0].get("value") < 5 ||
                                this.getElements('div.mail div.popup form.grid-span1 input')[1].get("value") < 5) {
                            alert('Не все поля заполнены');

                        } else {
                            var self = this;
                            new Request.JSON({url: url, method: 'post',
                                onSuccess: function(response) { // запрос выполнен уcпешно

                                    if (response.filds_valide == 0) {
                                        alert("E-mail или телефон указан неверно");
                                        return 0;
                                    }
                                    alert("Сообщение отправлено");
                                    self.getElements('div.mail div.popup form.grid-span1 textarea').set("value", "");
                                    self.getElement('div.mail div.popup').addClass('hide');
                                },
                                onComplete: function() {
                                }
                            }).send(this.getElements('div.mail div.popup form.grid-span1')[0]);
                        }
                        break;
                }
            })


        </script>
    </noindex>
    <!-- include virtual="/html/common/help_block_right.html"-->

</div>

<!--    .END Left Panel    -->
<!--    .BEGIN Main Panel    -->

<div class="main-panel span9">

    <div class="head-box">
        Моё меню                        </div>



    <div class="publications-alert" id="alert__publications_show_3new">

        <a class="float-r" style="padding: 10px" href="javascript:void(0);" onclick="$('alert__publications_show_3new').setStyle('display', 'none');
                        Cookie.write('ria_sspc_3030847', 1);"><img src="http://img6.auto.ria.ua/images/demo/close.png" alt="" /></a>

        <a class="more__publications" target="_blank" href="/help/file_674.html">Узнать больше о публикациях</a>


        <div class="wrapper__publications">


            <div class="head__publications bold">
                Поздравляем!
            </div>

            <p class="size17">

                Вам начислено в подарок <strong> бесплатные публикации!</strong>


            </p>

            <div class="descriptin__publications">

                <p>Вы можете использовать их для публикации объявлений на AUTO.ria.ua</p>

                <p>Следующие бесплатные публикации будут начислены на Вашу учетную запись <strong>19 Августа 2013</strong>.</p>

                <p>Внимательно используйте бесплатные публикации. После публикации объявления и последующего удаления в архив, публикации не возобновляются.</p>

                <p>
                    Если Вам нужно более 3 публикаций воспользуйтесь
                    <strong class="underline-dotted" title="Платные публикации доступны после использования 3 бесплатных публикаций. Нажмите &quot;Добавить объявление&quot; и  следуйте указаниям меню">платными публикациями</strong>
                    или купите коммерческий пакет “Автопродажа” и публикуйте со значительными скидками.
                </p>


            </div>

            <a class="button green bold" href="/add_auto.html">Добавить обьявление</a>
            <a class="button green bold" href="/autoseller/addpackage/">Купить пакет "Автопродажа"</a>

        </div>

    </div>
    <div class="wrapper-user-card">
        <div class="rocon box-wrapper">
            <div class="boxed">
                <div class="user-advanced-bar">
                    <div class="bar-advance boxed">
                        <div class="desc-adv">
                            <div>

                                На Вашем Личном счету:

                            </div>

                            <a href='https://oplaty.ria.ua/auto/help/file_473.html' target="_blank" class="size11 grey">

                                Что такое Личный счет?

                            </a>

                            <span class="float-l" style="cursor:pointer;" onclick="location.href = '/fishki-optom/?page=0#fishki-opt-history-btn'" title="Посмотреть отчет и пополнить счет фишек">

                                У Вас на счету:

                                <span class="red"><strong>0</strong></span> 

                                фишек

                            </span>
                        </div>
                        <div class="count-adv text-c">
                            <div class="price">
                                <strong class="size18 green">0</strong> грн.
                            </div>
                            <a href='https://oplaty.ria.ua/auto/' target="_blank" class="span1 button green mini">
                                пополнить                                                </a>
                        </div>
                    </div>
                    <div class="bar-advance boxed">
                        <div class="desc-adv">
                            <div style="margin-bottom: 8px">

                                Доступно публикаций:

                            </div>
                            <a href="/help/publications" target="_blank" class="size11 grey">

                                Что такое "Публикация"?

                            </a>
                            <div style="padding-top: 5px;">

                                Начислятся:

                            </div>

                        </div>

                        <div class="count-adv text-c">
                            <div class="price green">
                                <strong class="size18">3</strong> 

                                публикаций

                            </div>
                            <a href="/autoseller/addpackage/" target="_blank" class="span1 button green mini">

                                добавить

                            </a>
                            <div style="padding-top: 5px;">19 Августа 2013</div>
                        </div>

                    </div>
                </div>

                <img class="user-avatar" width="46" src="http://img.auto.ria.ua/img/common/test/photo.png" />
                <div class="personal-user-data">
                    <div class="myname overflow">
                        <strong class="size15"><?php echo Zend_Auth::getInstance()->getIdentity()->username; ?></strong>
                        <a href="/user/edit" target="_blank" class="grey size11">
                            <i class="icon-edit"></i> редактировать
                        </a>
                    </div>
                    <p class="item-row">
                        <i class="icon-mobile"></i><?php echo '(' . substr(Zend_Auth::getInstance()->getIdentity()->phone, 0, 3) . ') ' . substr(Zend_Auth::getInstance()->getIdentity()->phone, 3, 3) . '-' . substr(Zend_Auth::getInstance()->getIdentity()->phone, 6, 2) . '-' . substr(Zend_Auth::getInstance()->getIdentity()->phone, 8, 2) ; ?></p>

                    <p class="item-row">
                        <i class="icon-email"></i> <?php echo Zend_Auth::getInstance()->getIdentity()->email; ?></p>

                    <p class="item-row">
                        <i class="icon-id-item"></i> 
                        <span class="grey size11">
                            Ваш клиентский номер:
                        </span> 
                         <?php echo $this->data->id; ?>
                    </p>
                </div>
            </div>
        </div>
    </div>


    <section class="boxed navigation-menu">

        <div class="item">

            <a href="/add_auto.html" target="_blank" class="link" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_Add', 'Menu'])">
                <i class="navigation add-cars"></i>
                Добавить<br/> объявление                                </a>

        </div>

        <div class="item">

            <a href="/?target=user&event=myauto&section=all&viewType=all" target="_blank" class="link" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_All', 'Cars']);">
                <i class="navigation my-offers"></i>
                Мои<br/> объявления                                </a>

        </div>


        <div class="item">

            <a href="/myservice/" target="_blank" class="link" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_My_Service', 'Myservice']);">
                <i class="navigation commerc-ser"></i>
                Коммерческие<br/> сервисы                                </a>

        </div>


        <div class="item">

            <a href="/?target=user&event=mynotifications" target="_blank" class="link" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_All_Notifications', 'Notifications']);">
                <i class="navigation my-notifi"></i>
                Уведомления                                </a>

        </div>

        <div class="item">

            <a href="/?target=user&event=redug" target="_blank" class="link" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_My_Profile', 'My_Account']);">
                <i class="navigation my-profile"></i>
                Моя анкета                                </a>

        </div>


        <div class="item">

            <a href="/mobile_app/" target="_blank" class="link" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_Mobile_App', 'Promo']);">
                <i class="navigation mobile-aps"></i>
                Мобильное<br/> приложение                                </a>

        </div>

    </section>


    <section class="row">
        <div class="span6">
            <div class="head-box line">
                Дополнительные возможности                                </div>

            <p>
                Спасибо, что пользуетесь сайтом AUTO.ria.ua. Вы используете еще не все 
                возможности сайта. Также Вы можете:                                </p>

            <dl class="unordered-list">
                <dd>
                    <a href="/promo_view/" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_Promo_auto', 'Dop']);">Поднять объявления при поиске</a>
                </dd>
                <dd>
                    <a target="_blank" href="/autoseller/addpackage/" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_Click_on_Link_Autoseller', 'Dop']);">Публиковать объявления со скидкой</a>
                </dd>
                <dd>
                    <a target="_blank" href="/myservice/#publish_in_catalogs" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_Promo_auto', 'Dop']);">Разместить информацию в каталогах</a>
                </dd>
                <dd>
                    <a target="_blank" href="/subscribe#information_subscribe" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_My_Service', 'Dop']);">Получать рассылки про обновления, акции, конкурсы</a>
                </dd>
                <dd>
                    <a target="_blank" href="/subscribe#new_auto_subscribe" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_Subscribe', 'Dop']);" >Получать рассылки о новых предложениях авто</a>
                </dd>
            </dl>

            <div class="head-box line">
                Настройки                                </div>
            <style>
                .action-bar .tooltip{
                    width: 65px;
                }

            </style>
            <dl style="margin-top: 15px">
                <dd class="elem">
                    <div class="action-bar">
                        <span class="item-check">
                            <input id="chebox_contact_via_email" type="checkbox" value="1" >
                        </span>
                    </div>
                    <label for="chebox_contact_via_email">

                        Разрешить контактировать со мной через e-mail

                    </label>

                </dd>
                <dd class="elem">
                    <div class="action-bar">
                        <span class="item-check">
                            <input id="subscribe_user_to_news"  type="checkbox" value="2" checked >

                        </span>
                    </div>
                    <label for="subscribe_user_to_news" >

                        Получать рассылки про обновление, акции, конкурсы

                    </label>
                </dd>
                <dd class="elem">
                    <div class="action-bar">
                        <span class="item-check">
                            <input id="chebox_show_page_user" type="checkbox" value="3"  >
                        </span>
                    </div>
                    <label for="chebox_show_page_user">

                        Отображать мою личную страницу на сайте

                    </label>
                </dd>
            </dl>

            <dl class="unordered-list">
                <dt>

                Также вы можете:

                </dt>
                <dd>
                    <a target="_blank" href="/page_user/3030847/">

                        Посмотреть как выглядит Личная страница

                    </a>
                </dd>
                <dd>
                    <a href="javascript:void(0);" onClick="new Ria_Auto_Common_Popup_ConfirmPhone({'section': 'registration', 'phone': {'phone_full_formatted': '(050) 112-22-11', 'number': '1122211', 'code': '050', 'is_mobile': 1}});
                return false;">
                        Подтвердить свой номер телефона                                            </a>
                </dd>
                <dd>
                    <a href="/user/change_password.html" onclick="_gaq.push(['_trackEvent', 'Central_Menu_Target_User', 'Click_on_Link_Change_Password', 'Settings']);">
                        Изменить пароль                                        </a>
                </dd>
                <dd>
                    <a id="delete_user_account" href="javascript:void(0);">
                        Удалить эту учетную запись                                            </a>

                    <div id="popup_delete_user_account" class="popup  uarr __left hide" style="width: 380px">
                        <form class="grid wrapper">
                            <a id="popup_delete_user_account_close" class="close" href="javascript:void(0);">×</a>
                            <div class="title line">

                                Удаление учетной записи

                            </div>
                            <p>

                                Вы действительно хотите удалить свою учетную запись?

                            </p>
                            <div class="button-bar">
                                <input id="popup_delete_user_account_confirm" onclick="location.href = '/ph/mymenu/deleteaccount/';
                return false;" type="submit" class="button green" value="Удалить">
                                <a href="javascript:void(0);" id="popup_delete_user_account_close_button" class="button">
                                    Отменить                                                            </a>
                            </div>
                        </form>
                    </div>
                </dd>
            </dl>
        </div>
        <div class="span3">
            <!--                                <a href="#" target="_blank">
                                                <img src="http://bn.ria.ua/www/images/d5158c029296f0f68d70ecf9f1c459f5.png" width="220" alt="" />
                                            </a>-->
        </div>
    </section>

</div>
<!--    .END Main Panel    -->

