 <div class="row user-panel">
            <div style="float: right;" class="logout span3">
                <i class="icon-user"></i>
                <a href="/login.html?exit=yes&from_url=%2Fadd_auto.html" >
                    Войти под другим пользователем
                </a>
            </div>
            <div class="baseinfo span3">
                <span class="title">
                    Продавец:
                </span>
                <div class="panel-user-info">
                    <img class="avatar-smoll" src="http://img.auto.ria.ua/images/no-photo/no-photo-user-50x50.gif">
                    <dl class="user-info">
                        <dt class="item name">
                        Сергей
                        </dt>
                        <dd class="item">
                            Харьков
                        </dd>
                    </dl>

                </div>
            </div>
            <div class="offset3 datainfo">
                <div class="row">
                    <div class="span3 contact-data">
                        <p>
                            (093) 123-69-91
                            <a href="/?target=user&event=redug" title="Редактировать контактные данные" target="_blank"><i class="icon-edit"></i></a>
                        </p>
                        <p>
                            sergey.veretilo@gmail.com
                        </p>
                    </div>
                    <div class="offset3 contact-data">
                        <p>
                            <span class="font-13">Доступно публикаций:</span>
                            <span class="green">
                                <span id="user_publications_count" class="size-18 bold">3</span>
                            </span>
                        </p>
                        <p>Что такое <a href="http://auto.ria.ua/help/publications/" target="_blank">“Публикация”</a>?</p>
                    </div>
                </div>
            </div>
        </div>