<div id=":yt" class="ii gt m14087f307416f93e adP adO">
          <div id=":yu" style="overflow: hidden;">
              <u></u>
              <div style="margin:0">
                  <div style="font:13px/100% Arial;color:#424242">
                      <div style="width:100%;min-height:38px;border-bottom:3px solid #d00000;background:#f7f6f1">
                          <table style="width:700px;margin:0 auto">
                              <tbody>
                                  <tr>
                                      <td style="font-size:13px">
                                          <a target="_blank" style="float:left" href="http://autosale">
                                              <img width="141" height="22" alt="Autosale" title="Логотип Autosale" src="http://img6.auto.ria.ua/images/demo/subscribe/logo-auto.png">
                                          </a>
                                      </td>
                                      <td>
                                          <a target="_blank" style="float:right" href="http://autosale">
                                              <img width="96" height="48" alt="Логотип Autosale" title="Логотип Autosale" src="http://img6.auto.ria.ua/images/demo/subscribe/logo-ria.png">
                                          </a>
                                          <a target="_blank" style="font-weight:bold;margin-top:10px;color:#1d5873;line-height:15px;text-decoration:none;float:right" href="http://autosale/catalog/add/step/autoinfo">
                                              <img width="14" height="14" src="http://img6.auto.ria.ua/images/demo/subscribe/ico-add.jpg" style="float:left;margin-right:5px">
                                              Добавить объявление
                                          </a>
                                          <a target="_blank" style="font-weight:bold;margin-top:10px;color:#1d5873;line-height:15px;margin-right:15px;text-decoration:none;float:right" href="http://autosale">
                                              <img width="13" height="14" src="http://img6.auto.ria.ua/images/demo/subscribe/ico-search.jpg" style="float:left;margin-right:5px">
                                              Поиск авто
                                          </a>
                                      </td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
           
                        <?php echo $this->layout()->content; ?>
                      
                      
                      <div style="width:100%;min-height:120px;border-top:3px solid #d00000;background:#f7f6f1;color:#8b876a">
                          <table style="width:700px;margin:0 auto">
                              <tbody>
                                  <tr>
                                      <td style="width:345px;border-right:1px dotted #ffce5d;min-height:115px">
                                          <div style="font-size:15px">Присоединяйтесь к нам в социальных сетях:</div>
                                          <div style="margin-top:20px;display:inline-block">
                                              <a target="_blank" title="AUTO.ria.ua в VKontakte" alt="AUTO.ria.ua в VKontakte" href="http://vk.com/auto_ria_ua" style="color:#8b876a;line-height:33px;text-decoration:none;float:left;margin-right:15px">
                                                  <img width="32" height="32" src="http://img6.auto.ria.ua/images/demo/subscribe/ico-vk-big.jpg" style="float:left;margin-right:5px">
                                                  <strong>Вконтакте</strong>
                                              </a>
                                              <a target="_blank" title="AUTO.ria.ua в Facebook" alt="AUTO.ria.ua в Facebook" href="http://www.facebook.com/AUTO.ria.ua" style="color:#8b876a;line-height:33px;text-decoration:none;float:left;margin-right:15px">
                                                  <img width="32" height="32" src="http://img6.auto.ria.ua/images/demo/subscribe/ico-fb-big.jpg" style="float:left;margin-right:5px">
                                                  <strong>Facebook</strong>
                                              </a>
                                              <a target="_blank" title="AUTO.ria.ua в Twitter" alt="AUTO.ria.ua в Twitter" href="http://twitter.com/auto_ria_ua" style="color:#8b876a;line-height:33px;text-decoration:none;float:left">
                                                  <img width="32" height="32" src="http://img6.auto.ria.ua/images/demo/subscribe/ico-tw-big.jpg" style="float:left;margin-right:5px">
                                                  <strong>Twitter</strong>
                                              </a>
                                          </div>
                                      </td>
                                      <td style="padding-left:30px;font-size:12px;line-height:15px">
                                          <p>
                                              Спасибо, что выбрали именно наш сайт!
                                              <br>
                                              Письмо не является «Спамом», полностью отвечает требованиям Постановления КМУ № 720 от 09.08.2005 г. и ст. 33 Закона Украины «О телекоммуникациях»
                                          </p>
                                          <p>
                                              <a target="_blank" style="font-weight:bold;color:#8b876a;text-decoration:none" href="http://auto.ria.ua/subscribe/?second_tab=1">Отписаться от рассылки.</a>
                                          </p>
                                      </td>
                                  </tr>
                              </tbody>
                          </table>
                          <div class="yj6qo"></div>
                          <div class="adL"> </div>
                      </div>
                      <div class="adL"> </div>
                  </div>
                  <div class="adL"> </div>
              </div>
              <div class="adL"> </div>
          </div>
      </div>
