<!DOCTYPE html>
<html lang="ru">
   <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
       
        <?php $this->headLink()->appendStylesheet('/css/main.css', 'screen'); ?>
        <?php $this->headLink()->appendStylesheet('/css/init-main.css', 'screen'); ?>
       
        <?php $this->headScript()->prependFile('/js/jquery-1.7.2.min.js'); ?>
         <?php $this->headScript()->appendFile('/js/main.js'); ?>
       <?php echo $this->headLink(); ?>
       <?php echo $this->headScript();?>

   </head>

<body class="ru">
      <div class="container-body">
        <!-- .BEGIN header -->
<header class="text">
    <div class="container">
        <div class="loginbar">

            <?php if(Zend_Auth::getInstance()->hasIdentity()){ ?>
               <?php echo '<b style="font-weight: bold;">'.Zend_Auth::getInstance()->getIdentity()->username .'</b>'; ?>
                          <a href="/user/logout" class="item">Выход</a>
               <?php } else { ?>
                      <a href="/user/register" class="item">регистрация</a>
                      <a href="/user/login" class="item">вход</a>
               <?php } ?>
                 
        </div>
        <nav class="head-menu">
            <a class="ria-ua" href='http://www.ria.ua/' title="Бесплатные объявления Украины"></a>
            <a class="logo-auto-ria select" href='http://auto.ria.ua/' title="Авториа - автосайт №1 Украины"></a>
            <a class="logo-dom-ria" href='http://dom.ria.ua/' title="Продажа и аренда недвижимости в Украине"></a>
            <a class="logo-rabota-ria" href='http://rabota.ria.ua/' title="Поиск работы в Украине"></a>
            <div class="top-drop">
                <a title="Лучшие туры для отдыха" href="http://travel.ria.ua/?utm_source=auto&utm_medium=link&utm_campaign=header" class="logo-travel-ria" target=""></a>
                <ol class="drop-menu">
                    <li><a title="Все гостиницы Украины" href="http://hotels.ria.ua" class="logo-hotels-ria" target=""></a></li>
                    <li><a title="Бронирование авиабилетов онлайн" href="http://avia.ria.ua" class="logo-avia-ria" target=""></a></li>
                </ol>
            </div>
        </nav>
    </div>
</header>
<!-- .END header -->

        <div class="panel-banner" id="outboard">
            
            <!--RIA baner-->
            <div id="search_banner_730x90">
                <div></div>
            </div>

            <!--/RIA baner-->
            
        </div>





        <div class="container" id="show_grid">
            <!-- .BEGIN HEAD -->
<div class="header">
    <a href="/" class="logo">
        <img src="http://img6.auto.ria.ua/images/logo.png" width="255" height="40" alt="AUTO.ria.ua" title="Авториа - автосайт №1 Украины" alt="Базар авто Авториа. Продажа бу автомобилей - объявления"/>
    </a>
    <div class="header-settings">
        <div class="langbar">
        
            <span class="item">
                <i class="icon-rus"></i>рус.
            </span>
            <a class="item" href="/uk/">
                <i class="icon-ukr"></i>укр.
            </a>
        
        <!-- <a class="item" href="/ru/">-->
        </div>

        <a href="/catalog/add/step/autoinfo" class="button green add-offer" title="Добавить объявление о продаже авто">
             Добавить объявление
        </a>

        <div class="informbar">
            <div class="location">
    <a href="javascript:void(0);"><span>Украина</span><i class="icon-arrou"></i></a>

    <div id ="head_location_popup" class="popup uarr __center hide">
        <div class="wrapper">
            <a href="javascript:void(0);" class="close">×</a>
            <div class="title bold" style="margin: 0; padding: 0;">
                Выберите город
            </div>
            <form class="grid grid-span1">
                <p class="rows">
                    <label class="label" for="select2">Область:</label>
                    <span class="indent select">
                        <select id="select" name="state_id" style="width: 135px;">
                            <option>Загрузка...</option>
                        </select>
                    </span>
                </p>
                <p class="rows">
                    <label class="label" for="select2">Город:</label>
                    <span class="indent select">
                        <select id="select2" name="city_id" style="width: 135px;">
                            <option value="0">Любая</option>
                        </select>
                    </span>
                </p>
                <div class="input">
                    <a href="javascript:void(0);" class="button">Сохранить</a>
                </div>
            </form>
        </div>
    </div>

</div>
            
    <div class="allotted newads">
        <a class="icon-reload" href="javascript:void(0);"></a>
        <div class="wrap">
            <div class="" value="1">
                <a href="/last/visit/" class="stretch">С последнего визита</a>
                <span class="count">
                    +<a href="/last/visit/"><span>0</span><i class="icon-arrou"></i></a>
                </span>
            </div>
            <div class="hide" value="2">
                <a href="/last/hour/" class="stretch">За последний час</a>
                <span class="count">
                    <a href="/last/hour/"><span>613</span><i class="icon-arrou"></i></a>
                </span>
            </div>
            <div class="hide" value="3">
                <a href="/last/today/" class="stretch">За сегодня</a>
                <span class="count">
                    <a href="/last/today/"><span>4542</span><i class="icon-arrou"></i></a>
                </span>
            </div>
        </div>


        <div class="popup uarr __center hide">
            <div class="wrapper">
                <a href="javascript:void(0);" class="close">×</a>
                <div class="title line bold">
                    Выберите период
                </div>

                <div class="grid">
                    <div class="ckecklist">
                        <p class="item">
                            <span class="area blue">
                                + <strong value="1">0</strong>
                            </span>
                            <input type="radio" name="ria_adv_count" value="1" id="header_ads_count_from_last_visit" />
                            <label for="header_ads_count_from_last_visit">С последнего визита</label>
                        </p>
                        <p class="item">
                            <span class="area blue">
                                <strong value="2">613</strong>
                            </span>
                            <input type="radio" name="ria_adv_count" value="2" id="header_ads_count_per_hour" />
                            <label for="header_ads_count_per_hour">За последний час</label>
                        </p>
                        <p class="item">
                            <span class="area blue">
                                <strong value="3">4542</strong>
                            </span>
                            <input type="radio" name="ria_adv_count" value="3" id="header_ads_count_per_day"/>
                            <label for="header_ads_count_per_day">За сегодня</label>
                        </p>
                    </div>
                    <a href="javascript:void(0);" class="button">Сохранить</a>

                </div>
            </div>

        </div>
    </div>

        </div>

    </div>
    
    
    
</div>
<!-- .END HEAD -->
            <!-- .BEGIN main menu -->

<div class="main-menu" id="head_main_menu">

    <div class="tabs" load_content='/pseudo_services/head_menu_items/0?lang_id=2' tab="0">
        <i class="icon-search-red"></i>
        <div class="window hide">
            <div class="iframe" onmouseover="_gaq.push(['_trackEvent', 'Quick search', 'Mouse_on_Search_tab', 'Search']);"><iframe></iframe></div>
            <div style="width: 325px;" class="wrapper">
                <!--include virtual="/pseudo_services/head_menu_items/0?lang_id=${lang_id}" -->
            </div>
        </div>
    </div>

    <div class="tabs hide" tab="1">
         <a href="/mymenu.html" >Мое меню</a>
        <div class="window hide">

            <div class="iframe"><iframe></iframe></div>
            <div class="wrapper" style="width: 400px;">

                <!-- include virtual="/static/target/columns/event/user_info_menu_block/?lang_id={$smarty.session.lang_id}&type_block=1&sessionUserId=$sessionUserId&ria_new=1"
<dl class="unordered-list">
include virtual="/static/target/columns/event/one_left_menu_block/?lang_id={$smarty.session.lang_id}&partName=menu&sessionUserId=$sessionUserId&page_end=1&ria_new=1"
</ul>-->




                <dl class="column unordered-list" style="width:180px;">
                    <!-- Search form menu-->
    <p class="headbar bold"><a href="/search.html">Поиск авто</a></p>
    <form class="grid fast-search" id="main_menu_search" action="/" method="get">
        <div class="hidden">
            <input type="hidden" value="search" name="target" filter_type="old">
            <input type="hidden" value="little" name="event" filter_type="old">

            <input type="hidden" value="new" name="target" filter_type="new" class="hide">
            <input type="hidden" value="view" name="event" filter_type="new" class="hide">

            <input type="hidden" value="0" name="category_id">
        </div>
        <div class="row type-search">
            <label for="item1" class="span2">
                <input type="radio" name="radio" id="item1" value="oldAutos" checked="checked">
                авто б/у
            </label>
            <label for="item2" class="span2">
                <input type="radio" name="radio" id="item2" value="newAutos">
                новые авто
            </label>
        </div>

        <p class="rows" filter_type="old">
            <label for="" class="label">Марка:</label>
            <span class="select">
                <select class="span3" name="marka" content="marka_old" onchange="_gaq.push(['_trackEvent', 'Quick search', 'Select_Marka', 'B-u search']);return true;">
                    <option value="0">Любая</option>
                    
                </select>
            </span>
        </p>
        <p class="rows hide" filter_type="new">
            <label for="" class="label">Марка:</label>
            <span class="select">
                <select class="span3" onchange="_gaq.push(['_trackEvent', 'Quick search', 'Select_Marka', 'New search']);return true;" name="marka_id" content="marka_new" >
                    <option value="0">Любая</option>
                    
                </select>
            </span>
        </p>

        <p class="rows" filter_type="old">
            <label for="" class="label">Модель:</label>
            <span class="select">
                <select class="span3" content="model_old" onchange="_gaq.push(['_trackEvent', 'Quick search', 'Select_Model', 'B-u search']);return true;" name="model">
                    <option value="0">Любая</option>
                </select>
            </span>
        </p>
        <p class="rows hide" filter_type="new">
            <label for="" class="label">Модель:</label>
            <span class="select">
                <select class="span3" content="model_new" onchange="_gaq.push(['_trackEvent', 'Quick search', 'Select_Model', 'New search']);return true;" name="model_id">
                    <option value="0">Любая</option>
                </select>
            </span>
        </p>

        <p class="rows" filter_type="old">
            <label for="" class="label">Год выпуска:</label>
            <span class="indent">
                от
                <select class="years" onchange="_gaq.push(['_trackEvent', 'Quick search', 'Select_Year_from', 'B-u search']);return true;" id="" name="s_yers">
                    <option value="0">Любой</option>
                    
                </select>
                <em class="mdash">&mdash;</em>
                до
                <select class="years" onchange="_gaq.push(['_trackEvent', 'Quick search', 'Select_Year_to', 'B-u search']);return true;" id="" name="po_yers">
                    <option value="0">Любой</option>
                    
                </select>
            </span>
        </p>

        <p class="rows" filter_type="old">
            <label for="" class="label">Регион:</label>
            <span class="select">
                <select class="span3" id="" onChange="_gaq.push(['_trackEvent', 'Quick search', 'Select_Region', 'B-u search']);return true;" name="state">
                    <option value="0">Любой</option>
                    
                </select>
            </span>
        </p>
        <p class="rows hide" filter_type="new">
            <label for="" class="label">Регион:</label>
            <span class="select">
                <select class="span3" id="" onChange="_gaq.push(['_trackEvent', 'Quick search', 'Select_Region', 'New search']);return true;" name="city">
                    <option value="0">Любой</option>
                    
                </select>
            </span>
        </p>

        <p class="rows">
            <label for="" class="label bold">Цена:</label>
            <span class="select">
                <input type="text" placeholder="от" class="price" onclick="_gaq.push(['_trackEvent', 'Quick search', 'Input_Price_from', 'Search']);" name="price_ot">
                <em class="mdash">&mdash;</em>
                <input type="text" placeholder="до" class="price" onclick="_gaq.push(['_trackEvent', 'Quick search', 'Input_Price_to', 'Search']);" name="price_do">
                <select class="currency" id="" onchange="_gaq.push(['_trackEvent', 'Quick search', 'Select_Currency', 'Search']); return true;" name="currency">
                    <option value="1">$</option>
                    <option value="2">€</option>
                    <option value="3">грн.</option>
                </select>
            </span>
        </p>

        <div class="submit-form">

            <span class="button-icon">
                <i class="icon-search-white"></i>
                <input type="submit" value="Поиск" class="button blue large">
            </span>

            <p class="checkrows" filter_type="old">
                <input type="checkbox" id="check1" name="with_photo" value="1">
                <label for="check1">
                    <i class="icon-photo-red"></i>
                    только с фото
                </label>
            </p>

            <a filter_type="old" href="/search.html" ext_search="true">
                 Расширенный поиск
            </a>
        </div>
    </form>


                </dl>

                <ul class="column unordered-list" style="width: 180px">
                    <li>
                        <a title="Мой блокнот" href="/notepad.html" >
                           Мой блокнот
                    </a>

        <!--
# if expr="$bookmarks_count!=0"
<strong class="blue">
#echo var="bookmarks_count"
</strong>
# endif -->
                </li>
                <li>
                    <a title="Моя анкета" href="/?target=user&event=redug" >
                       Моя анкета
                </a>
            </li>
            <li>
                <a title="Коммерческие сервисы" href="/myservice/" onclick="_gaq.push(['_trackEvent', 'My_Menu_Tab', 'Click_on_Link_My_Service', 'Myservice'])">
                   Коммерческие сервисы
            </a>
        </li>
        <li>
            <a title="Поменять пароль" href="/user/change_password.html" >
               Поменять пароль
        </a>
    </li>
    <li>
        <a title="Рассылка" href="/subscribe" >
           Рассылка
    </a>
</li>
<li>
    <a title="Мои поиски" href="/?target=user&event=searchHistory" >
       Мои поиски
</a>
</li>
<li>
    <a class="new" title="Мой Черный список" href="/user/blacklist" >
       Мой "Черный список"
</a>
</li>

</ul>
<div class="menu__bottom-panel">
    <a class="link-add" href="/catalog/add/step/autoinfo" title="Добавить объявление" >
       Добавить объявление
</a>
</div>
</div>
</div>
</div>


<div class="tabs" tab="2">
    <a href="/" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Used_Cars', 'Menu'])">Автомобили б/у</a>
    <div class="window hide">
        <div class="iframe"><iframe></iframe></div>
        <div style="width: 340px;" class="wrapper">
            <p class="headbar bold">
                <a href="/search" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Used_Cars', 'Search'])">
                   Автомобили б/у
            </a>
        </p>
        <ul class="column unordered-list">
            <li><a href="/legkovie/" title="Легковые" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Legkovie', 'Сatalog'])">Легковые</a></li>
            <li><a href="/moto/" title="Мото" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Moto', 'Сatalog'])">Мото</a></li>
            <li><a href="/vodnyj_transport/" title="Водный транспорт" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Vodnyj_Transport', 'Сatalog'])">Водный транспорт</a></li>
            <li><a href="/spectehnika/" title="Спецтехника" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Spectehnika', 'Сatalog'])">Спецтехника</a></li>
            <li><a href="/trailer/" title="Прицепы" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Trailer', 'Сatalog'])">Прицепы</a></li>
            <li><a href="/truck/" title=" Грузовики" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Truck', 'Сatalog'])"> Грузовики</a></li>
            <li><a href="/bus/" title="Автобуси" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Bus', 'Сatalog'])">Автобуси</a></li>
            <li><a href="/autohouse/" title="Автодома" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Autohouse', 'Сatalog'])">Автодома</a></li>
            <li><a href="/air_transport/" title="Воздушный транспорт" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Air_Transport', 'Сatalog'])">Воздушный транспорт</a></li>

        </ul>
        <ul class="column unordered-list" >
            <li><a href="/search.html" title="Поиск авто" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Search_Cars', 'Search'])">Поиск авто</a></li>
            <li><a href="/hots/" title="Горячие предложения" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Hots', 'Сatalog'])">Горячие предложения</a></li>
            <li><a href="/retro/" title="Ретро автомобили" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Retro', 'Сatalog'])">Ретро автомобили</a></li>
            <li><a href="/autointer/" title="Авто из-за рубежа" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Autointer', 'Сatalog'])">Авто из-за рубежа</a></li>
            <li><a href="/avtovikup/" title="Автовыкуп" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Avtovikup', 'Service'])">Автовыкуп</a></li>
            <li><a href="/kredit_auto/" class="new" title="Кредитные авто" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Kredit', 'Сatalog'])">Кредитные авто</a></li>
            <li><a href="/newauto/Отзывы/Каталог/" class="new" title="Отзывы об авто" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Car_Reviews', 'Reviews'])">Отзывы об авто</a></li>
            <li><a href="/diagnostika-promo/" class="new" title="Проверенные авто" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Diagnostika', 'Promo'])">Проверенные авто</a></li>
        </ul>
        <div class="menu__bottom-panel">
            <a class="link-add" href="/add_auto.html" title="Добавить объявление" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Add', 'Menu'])" >
               Добавить объявление
        </a>
    </div>
</div>
</div>
</div>
<div class="tabs" tab="3">
    <a href="/newauto/" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Newauto', 'Menu'])">Новые авто</a>
    <div class="window hide">
        <div class="iframe"><iframe></iframe></div>
        <div style="width: 345px;" class="wrapper">
            <p class="headbar bold">
                <a href="/newauto/">Новые авто</a>
            </p>
            <ul class="column unordered-list">
                <li><a href="/newauto/" title="Поиск новых авто" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Newauto', 'Search'])">Поиск новых авто</a></li>
                <li><a href="/new_auto/master_search/" title="Мастер поиска" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Master_Search', 'Search'])">Мастер поиска</a></li>
                <li><a href="/newauto/catalogue/" title="Каталог новых авто" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Newauto_Сatalog', 'Сatalog'])">Каталог новых авто</a></li>
                <li><i class="icon-reliable-partner"></i><a href="/reliable-partner/" title="Надежный партнер" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Reliable_Partner', 'Promo'])">Надежный партнер</a></li>
            </ul>
            <ul class="column unordered-list">
                <li><a href="/newauto/avtosaloni/" title="Автосалоны" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Avtosalon', 'Сatalog'])">Автосалоны</a></li>
                <li><a class="new" href="/newauto/motosaloni/" title="Мотосалоны" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Motosalon', 'Сatalog'])">Мотосалоны</a></li>
                <li><a href="/news/actions/" title="Акции автосалонов" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Newauto_Actions', 'News'])">Акции автосалонов</a></li>
                <li><a href="/newauto/Отзывы/Каталог/" class="new" title="Отзывы об авто" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Car_Reviews', 'Reviews'])">Отзывы об авто</a></li>
            </ul>
            <div class="menu__bottom-panel">
                <a class="link-add" href="/avtosaloni/addinfo/" title="Добавить Автосалон" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Add_Avtosalon', 'Menu'])" >
                   Добавить Автосалон
            </a>
            <em class="mdash">|</em>
            <a class="link-add" href="/motosalon/addinfo/" title="Добавить Мотосалон" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Add_Motosalon', 'Menu'])" >
               Добавить Мотосалон
        </a>
    </div>
</div>
</div>
</div>
<div class="tabs" tab="4">
    <a href="javascript:void(0);">Все для авто</a>
    <div class="window hide">
        <div class="iframe"><iframe></iframe></div>
        <div style="width: 565px;" class="wrapper">
            <div class="column" style="width: 155px">
                <dl class="unordered-list">
                    <dt>Сервисы</dt>
                    <dd><a href="/avtovikup/" title="Автовыкуп" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Avtovikup', 'Service'])">Автовыкуп</a></dd>
                    <dd><a href="/autolombardy/" title="Автоломбарды" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Autolombardy', 'Service'])">Автоломбарды</a></dd>
                    <dd><a href="/autoservice/" title="Автосервисы" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Autoservice', 'Service'])">Автосервисы</a></dd>
                    <dd><a href="/avtorazborka/" title="Авторазборка" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Avtorazborka', 'Service'])">Авторазборка</a></dd>
                    <dd><a href="/avtorazborka/#stolzakazov" onclick="_gaq.push(['_trackEvent', 'Stol_Zakazov_Zapch', 'Add_Aplication', 'Main_AUTO.ria.ua']);" title="Стол заказов запчастей">Стол заказов запчастей</a></dd>
                    <dd><a href="/strahovanie/" title="Автострахование" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Strahovanie', 'Service'])">Автострахование</a></dd>
                    <dd><a href="http://market.auto.ria.ua/tehpomosch" target="_blank" title="##autohelp##" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Tehpomosch', 'Market'])">Автопомощь</a></dd>
                    <dd><a href="/rastamozhka_avto/" title="Растаможка авто" onclick="_gaq.push(['_trackEvent', 'Used_Cars_Tab', 'Click_on_Link_Rastamozhka', 'Сatalog'])">Растаможка авто</a></dd>
                </dl>
            </div>
            <div class="column">
             <dl class="unordered-list">
                <dt>
                    Товары от
                    <a href="http://market.auto.ria.ua" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Market', 'Market'])">
                        <i class="ico-market"></i>
                    </a>
                </dt>
                <dd><a href="http://market.auto.ria.ua/shina" title="Шины" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Shina', 'Market'])">Шины</a></dd>
                <dd><a href="http://market.auto.ria.ua/diski" title="Диски" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Diski', 'Market'])">Диски</a></dd>
                <dd><a href="http://market.auto.ria.ua/car_seats/" title="Детские автокресла" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Krisla', 'Market'])">Детские автокресла</a></dd>
                <dd><a href="http://market.auto.ria.ua/avtochehlu" title="Чехлы на сиденья" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Avtochehlu', 'Market'])">Чехлы на сиденья</a></dd>
                <dd><a href="http://market.auto.ria.ua/kovriki/" title="Коврики" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Kovriki', 'Market'])">Коврики</a></dd>
                <dd><a href="http://market.auto.ria.ua/farkop/" title="Фаркопы" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Farkop', 'Market'])">Фаркопы</a></dd>

                <dt>&nbsp;</dt>
                <dd><a href="http://zapchasti.ria.ua/" title="Запчасти" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Zapchast_Catalog', 'Ria'])">Запчасти</a></dd>
                <dd><a href="http://dom.ria.ua/garage/" title="Гаражи" target="_blank" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Garage_Catalog', 'Dom'])">Гаражи</a></dd>
               <dd><a href="/document/" title="Автодокументы" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Document', 'Poleznoe'])">Автодокументы</a></dd>
            </dl>
            </div>
            <div class="column" style="width: 195px">
                <dl class="unordered-list">
                    <dt>Полезное</dt>
                    <dd><a href="/avtoshkola/" title="Автошколы" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Avtoshkola', 'Poleznoe'])">Автошколы</a></dd>
                    <dd><a href="/online_pdd/" title="Билеты ПДД онлайн" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Pdd_online', 'Poleznoe'])">Билеты ПДД онлайн</a></dd>
                    <dd><a href="/forum" title="Автофорум" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Forum', 'Poleznoe'])">Автофорум</a></dd>
                    <dd><a href="/humor/" title="Автоюмор" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Humor', 'Poleznoe'])">Автоюмор</a></dd>
                    <dd><a href="/autoclubs/" title="Автоклубы" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Autoclubs', 'Poleznoe'])">Автоклубы</a></dd>
                    <dd><a href="http://link.auto.ria.ua/" title="Автосайты" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Links', 'Poleznoe'])">Автосайты</a></dd>
                    <dd><a href="/automagazine/" title="Журналы" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Magazine', 'Poleznoe'])">Журналы</a></dd>
                    <dd><a href="/compare/" title="Надежность авто" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Compare', 'Poleznoe'])">Надежность авто</a></dd>
                    <dd><a href="http://lanos.com.ua/" title="Все про Lanos" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Lanos', 'Poleznoe'])">Все про Lanos</a></dd>
                    <dd><a href="/first_auto/" title="Покупаем первый автомобиль" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_First_Auto', 'Poleznoe'])">Покупаем первый автомобиль</a></dd>
                    <dd><a href="/newauto/Отзывы/Каталог/" class="new" title="Отзывы об авто" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Car_Reviews', 'Reviews'])">Отзывы об авто</a></dd>
                </dl>
            </div>

            <div class="menu__bottom-panel">
                <a href="/help/" title="Помощь" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Help', 'Poleznoe'])">Помощь</a>
                <em class="mdash">|</em>
                <a href="/news/novinki/" title="Нововведения" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Novinki', 'Poleznoe'])">Нововведения</a>
                <em class="mdash">|</em>
                <a class="new" href="/?target=view&event=lic" title="Соглашение о предоставлении услуг" onclick="_gaq.push(['_trackEvent', 'Newauto_Tab', 'Click_on_Link_Agreement', 'Poleznoe'])">Соглашение о предоставлении услуг</a>

            </div>
            <div class="menu__bottom-panel">
                <a class="link-add" href="/document/add.html" title="Добавить Автодокумент" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Add_Docum', 'Menu'])">Добавить Автодокумент</a>
                <em class="mdash">|</em>
                <a class="link-add" href="http://www.ria.ua/advertisement/addstep1" title="Добавить запчасть" onclick="_gaq.push(['_trackEvent', 'All_For_Auto_Tab', 'Click_on_Link_Add_Zapchast', 'Ria'])">Добавить запчасть</a>
            </div>


        </div>
    </div>

</div>
<div class="tabs" tab="5">
    <a href="/news/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_News', 'News'])">Новости</a>
    <strong class="blue"></strong>
    <div class="window hide">
        <div class="iframe"></div>
        <div class="wrapper" style="width: 412px;">
            

    <div class="column" style="min-width: 90px">
        <dl class="unordered-list">
            <dt>
            <a href="/news/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_All_News', 'News'])">Все новости</a>
            </dt>

            

                <dd>
                    
                        <a href="/news/events/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_events', 'News'])">События</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/auto/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_auto', 'News'])">Автомобили</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/autobusiness/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_autobusiness', 'News'])">Автобизнес</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/autolaw/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_autolaw', 'News'])">Автозакон</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/actions/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_actions', 'News'])">Акции</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/test_drive/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_test_drive', 'News'])">Тест-драйвы</a>
                    
                </dd>

            
        </dl>

    </div>
    <div class="column" style="width: 165px">
        <dl class="unordered-list">
            <dt>&nbsp;</dt>

            

        

                <dd>
                    
                        <a href="/news/autoservice_technology/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_Technology', 'News'])">Автосервис и Технологии</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/about_us/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_about_us', 'News'])">О нас пишут</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/avtoblog/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_avtoblog', 'News'])">Автоблоги</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/novinki/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_novinki', 'News'])">Нововведения</a>
                    
                </dd>

            

        </dl>
    </div>
    <div class="column" style="min-width: 105px; padding-right: 0;">
        <dl class="unordered-list">
            <dt>&nbsp;</dt>

            

        

                <dd>
                    
                        <a href="/news/subaru/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_subaru', 'News'])">Все о Subaru</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/bmw/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_bmw', 'News'])">Все o BMW</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/mini/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_mini', 'News'])">Все о MINI</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/rental_info/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_rental_info', 'News'])">Все о прокате</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/journals/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_journals', 'News'])">Онлайн журнал</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/konkurs/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_konkurs', 'News'])">Конкурсы</a>
                    
                </dd>

            

        

                <dd>
                    
                        <a href="/news/shanghai/" onclick="_gaq.push(['_trackEvent', 'News_Tab', 'Click_on_Link_shanghai', 'News'])">Шанхай-2013</a>
                    
                </dd>

            

        

        </dl>
    </div>


        </div>
    </div>




</div>
<div class="tabs" >
    <a href="/notepad.html" >
       <i class="icon-star-tab"></i> Блокнот
        <!-- FIX THIS to JavaScript-->
        <!-- # if expr="$bookmarks_count!=0"
<strong class="blue">
#echo var="bookmarks_count"
</strong>
# endif -->
    </a>
</div>

<span class="area">
          <i class="ico-new"></i>
     <a href="http://auto.ria.ua/news/events/206878/" target="_blank" class="insert-element"
        onclick="_gaq.push(['_trackEvent', 'Whats_New', 'Click_on_Yanukovich_poshlini', '/']);">
                  Янукович займется пошлинами
          
     </a>
  <!-- Page load array script time : 0.034149885177612
-->
</span>
</div>


<!-- .END main menu -->
            <!-- .BEGIN Pager -->
<div style="display: none;">
<!--<div>-->
    /blocks_search_ajax/breadcrumbs/search/?catalog_name=search&person_id=0
    <hr noshade="noshade">
</div>

<div class="panel-breadcrumbs">
    <h2 class="breadcrumbs" id="breadcrumbs">
        
            <a href="/" title="Продажа авто" id="breadcrumbs-/" class="item">Продажа авто</a>
            
        
            <a href="/search/" title="Расширенный поиск на Auto.ria.ua : продажа авто, автосалоны, каталог автомобилей, базар авто" id="breadcrumbs-/search/" class="item">Поиск авто</a>
            
        
    </h2>
    <div class="popup uarr __left" style="left: 100px; display: none;" id="breadcrumbs_popup_container">
        <div class="iframe">
            <iframe></iframe>
        </div>
        <div class="wrapper" >
            <div class="wrapper-group" id="breadcrumbs_popup_data">
        </div>
        </div>
    </div>
</div>


<!-- .END Pager -->
            <div class="row content-main">
                <!-- .BEGIN Main Panel -->

<!-- include virtual="/html/blocks/search_page/blocks/assync_banners_loader.html" -->


       
    
    
<?php echo $this->layout()->content; ?>



<!-- .END Main Panel -->




                <!-- .BEGIN Right Panel -->

                </div>
<!-- .END Right Panel -->
            </div>
        </div>
        <a href="/impressions" class="feedback"></a>
        
        
    </div>
    <!-- .BEGIN FOOTER -->
<footer>
    <div class="container">

        <div class="footer-menu">

            <div class="copyright">
                &copy; 2004-2013 RIA.ua.<br />
                Все права защищены
            </div>

            <div class="footer-signature">

                <nav class="menu-footer">
                    <a class="item" href='http://www.ria.ua/'>Объявления</a>
                    <a class="item active" href='http://auto.ria.ua/'>Автомобили</a>
                    <a class="item" href='http://dom.ria.ua/'>Недвижимость</a>
                    <a class="item" href='http://rabota.ria.ua/'>Работа</a>
                    <a class="item" href="http://hotels.ria.ua/">Гостиницы</a>
                    <a class="item" href="http://avia.ria.ua/">Билеты</a>
                </nav>

                <div class="clear"></div>

                <div class="left-bar__footer">

                    <a href="http://auto.ria.ua/price/">Реклама на сайте</a><br />

                    <!--i class="icon-mobile"></i-->
                    <a href="http://m.auto.ria.ua/">Мобильная версия</a><br />

                    <!--i class="icon-bezpeka"></i-->
                    <a href="http://bezpeka.ria.ua/">Безопасные сделки</a>


                </div>

                <div class="signature__footer">

                    <div class="right-bar__footer">
                        <a target="_blank" title="Prom.ua — здесь находят клиентов (откроется в новом окне)" href="http://prom.ua">Prom.ua</a><br />
                        
                        
                            <a target="_blank" href="/map/">Карта сайта</a><br/>
                        
                    </div>

                    <a href="http://auto.ria.ua/question/search/">Помощь</a><br />
                    <a target="_blank" href="http://auto.ria.ua/privacy-policy/">Политика конфиденциальности</a><br />
                    <a href="http://cobrand.ria.ua/">Партнерские программы</a>

                </div>

            </div>
        </div>
<!-- Yandex.Metrika counter -->

     
<noscript><div><img src="//mc.yandex.ru/watch/91244" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
     
<!-- /Yandex.Metrika counter -->


    <div id="vk_api_transport"></div>



<!-- MMI CMeter -->

<noscript>
<img
src="http://juke.mmi.bemobile.ua/bug/pic.gif?siteid=auto.ria.ua"
style="position:absolute;left:-1000px;"
alt=""
/>
</noscript>


<!-- /MMI CMeter -->

     </div>
</footer>
</body>
</html>