<!DOCTYPE HTML>
<html>

<head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
       
        <?php //$this->headLink()->appendStylesheet('/css/main.css', 'screen'); ?>
        <?php //$this->headLink()->appendStylesheet('/css/init-main.css', 'screen'); ?>
       
        <?php $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js');  ?>
        <?php //$this->headScript()->appendFile('/js/main.js');  ?>
       
        
        <?php echo $this->headScript();  ?>
       <?php echo $this->headLink();  ?>

       <?php // echo $this->headScript()->appendFile('/js/init_add.js');?>

   </head>


<body>
	<h1>Uploadify Demo</h1>
	<form>
		<div id="queue"></div>
		<input id="file_upload" name="file_upload" type="file" multiple="true">
	</form>

	<script type="text/javascript">
		<?php $timestamp = time();?>
		$(function() {
			$('#file_upload').uploadify({
				'swf'      : 'uploadify.swf',
				'uploader' : 'uploadify.php'
			});
		});
	</script>
</body>
</html>