<!DOCTYPE html>
<html lang="en">


    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <?php $this->headLink()->appendStylesheet('/css/init_mymenu_new2.css', 'screen'); ?>
        <?php $this->headLink()->appendStylesheet('/css/init_mymenu_new1.css', 'screen'); ?>

        <?php $this->headScript()->prependFile('/js/jquery-1.7.2.min.js'); ?>
        <?php //$this->headScript()->appendFile('/js/main.js'); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript();?>

    </head>
    <body>
        <div class="container-body">
            <!--   .BEGIN header   -->
            <header class="text">
                <div class="container">
                    <div class="loginbar">
                        <a href="/user/register" class="item">регистрация</a>
                        <a href="/login.html" class="item">вход</a>
                    </div>
                    <nav class="head-menu">
                        <a class="ria-ua" href='http://www.ria.ua/' title="Бесплатные объявления Украины"></a>
                        <a class="logo-auto-ria select" href='http://auto.ria.ua/' title="Авториа - автосайт №1 Украины"></a>
                        <a class="logo-dom-ria" href='http://dom.ria.ua/' title="Продажа и аренда недвижимости в Украине"></a>
                        <a class="logo-rabota-ria" href='http://rabota.ria.ua/' title="Поиск работы в Украине"></a>

                        <div class="top-drop">
                            <a title="Лучшие туры для отдыха" href="http://travel.ria.ua/?utm_source=auto&utm_medium=link&utm_campaign=header" class="logo-travel-ria" target=""></a>
                            <ol class="drop-menu">
                                <li><a title="Все гостиницы Украины" href="http://hotels.ria.ua" class="logo-hotels-ria" target=""></a></li>
                                <li><a title="Бронирование авиабилетов онлайн" href="http://avia.ria.ua" class="logo-avia-ria" target=""></a></li>
                            </ol>
                        </div>

                    </nav>
                </div>
            </header>
            <!--   .END header   -->

            <div class="container" id="show_grid">
                <!--   .BEGIN HEAD   -->
                <div class="header">
                    <a href="/" class="logo">
                        <img src="http://img6.auto.ria.ua/images/logo.png" width="255" height="40" alt="AUTO.ria.ua" title="Авториа - автосайт №1 Украины" alt="Базар авто Авториа. Продажа бу автомобилей - объявления"/>
                    </a>





                    <script type="text/javascript">
                        function set_logo(url, w, h) {
                            $$('a.logo img').set('src', url).set('width', w).set('height', h);
                        }

                        var date = new Date();
                        h = date['getHours']();
                        i = date['getMinutes']();
                        s = date['getSeconds']();
                        y = date['getFullYear']();
                        m = date['getMonth']() + 1;
                        d = date['getDate']();

                        m_holiday = 8; //месяц события
                        d_holiday_l = 24; //день месяца начала события
                        d_holiday_u = 26; //день месяца конца события
                        h_holiday_l = 1; //час месяца начала события
                        h_holiday_u = 24; //час месяца конца события

                        if (m == m_holiday && (d >= d_holiday_l && (d != d_holiday_l || h >= h_holiday_l - 1)) && (d <= d_holiday_u && (d != d_holiday_u || h <= h_holiday_u - 1))) {
                            set_logo('http://img6.auto.ria.ua/images/branding/logo/ru/dn_rus.png', 250, 35);
                            $$('a.logo img').setStyle('margin-top', '5px');
                        }
                    </script>



                    <div class="header-settings">
                        <div class="langbar">

                            <span class="item">
                                <i class="icon-rus"></i>рус.
                            </span>
                            <a class="item" href="/uk/">
                                <i class="icon-ukr"></i>укр.
                            </a>

                            <!--            <a class="item" href="/ru/">-->
                        </div>

                        <a href="/add_auto.html" class="button green add-offer" title="Добавить объявление о продаже авто">
                            Добавить объявление
                        </a>

                        <div class="informbar">
                            <div class="location">
                                <a href="javascript:void(0);"><span>Украина</span><i class="icon-arrou"></i></a>

                                <div id ="head_location_popup" class="popup uarr __center hide">
                                    <div class="wrapper">
                                        <a href="javascript:void(0);" class="close">×</a>
                                        <div class="title bold" style="margin: 0; padding: 0;">
                                            Выберите город
                                        </div>
                                        <form class="grid grid-span1">
                                            <p class="rows">
                                                <label class="label" for="select2">Область:</label>
                                                <span class="indent select">
                                                    <select id="select" name="state_id" style="width: 135px;">
                                                        <option>Загрузка...</option>
                                                    </select>
                                                </span>
                                            </p>
                                            <p class="rows">
                                                <label class="label" for="select2">Город:</label>
                                                <span class="indent select">
                                                    <select id="select2" name="city_id" style="width: 135px;">
                                                        <option value="0">Любая</option>
                                                    </select>
                                                </span>
                                            </p>
                                            <div class="input">
                                                <a href="javascript:void(0);" class="button">Сохранить</a>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>

                            <div class="allotted newads">
                                <a class="icon-reload" href="javascript:void(0);"></a>
                                <div class="wrap">
                                    <div class="" value="1">
                                        <a href="/last/visit/" class="stretch">С последнего визита</a>
                                        <span class="count">
                                            +<a href="/last/visit/"><span>0</span><i class="icon-arrou"></i></a>
                                        </span>
                                    </div>
                                    <div class="hide" value="2">
                                        <a href="/last/hour/" class="stretch">За последний час</a>
                                        <span class="count">
                                            <a href="/last/hour/"><span>590</span><i class="icon-arrou"></i></a>
                                        </span>
                                    </div>
                                    <div class="hide" value="3">
                                        <a href="/last/today/" class="stretch">За сегодня</a>
                                        <span class="count">
                                            <a href="/last/today/"><span>2542</span><i class="icon-arrou"></i></a>
                                        </span>
                                    </div>
                                </div>


                                <div class="popup uarr __center hide">
                                    <div class="wrapper">
                                        <a href="javascript:void(0);" class="close">×</a>
                                        <div class="title line bold">
                                            Выберите период
                                        </div>

                                        <div class="grid">
                                            <div class="ckecklist">
                                                <p class="item">
                                                    <span class="area blue">
                                                        + <strong value="1">0</strong>
                                                    </span>
                                                    <input type="radio" name="ria_adv_count" value="1" id="header_ads_count_from_last_visit" />
                                                    <label for="header_ads_count_from_last_visit">С последнего визита</label>
                                                </p>
                                                <p class="item">
                                                    <span class="area blue">
                                                        <strong value="2">590</strong>
                                                    </span>
                                                    <input type="radio" name="ria_adv_count" value="2" id="header_ads_count_per_hour" />
                                                    <label for="header_ads_count_per_hour">За последний час</label>
                                                </p>
                                                <p class="item">
                                                    <span class="area blue">
                                                        <strong value="3">2542</strong>
                                                    </span>
                                                    <input  type="radio" name="ria_adv_count" value="3" id="header_ads_count_per_day"/>
                                                    <label for="header_ads_count_per_day">За сегодня</label>
                                                </p>
                                            </div>
                                            <a href="javascript:void(0);" class="button">Сохранить</a>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>





                </div>
                <!--   .END HEAD   -->
                <!--   .BEGIN main menu   -->

                <div class="main-menu" id="head_main_menu">

                    <div class="tabs" load_content='/pseudo_services/head_menu_items/0?lang_id=2' tab="0">
                        <i class="icon-search-red"></i>
                        <div class="window hide">
                            <div class="iframe" onmouseover="_gaq.push(['_trackEvent', 'Quick search', 'Mouse_on_Search_tab', 'Search']);"><iframe></iframe></div>
                            <div style="width: 325px;" class="wrapper">
                                <!--include virtual="/pseudo_services/head_menu_items/0?lang_id=${lang_id}" -->
                            </div>
                        </div>
                    </div>

                    <div class="tabs " tab="1">
                        <a href="/mymenu/" >Мое меню <i id="icon_notifications" class=""></i></a>
                        <div class="window hide">

                            <div class="iframe"><iframe></iframe></div>
                            <div class="wrapper" style="width: 400px;">

                                <!--             include virtual="/static/target/columns/event/user_info_menu_block/?lang_id={$smarty.session.lang_id}&type_block=1&sessionUserId=$sessionUserId&ria_new=1"
                                                <dl class="unordered-list">
                                                    include virtual="/static/target/columns/event/one_left_menu_block/?lang_id={$smarty.session.lang_id}&partName=menu&sessionUserId=$sessionUserId&page_end=1&ria_new=1"
                                                </ul>-->

                                <div id="sub_menu_items_from_pseudo_servises"></div>




                                <!-- include virtual="/pseudo_services/head_menu_items/1?lang_id=${lang_id}&client_id=${client_id}" -->





                                <div class="menu__bottom-panel">
                                    <a class="link-add" href="/add_auto.html" title="Добавить объявление"  >
                                        Добавить объявление
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="tabs" tab="2">
                        <a href="/" >Автомобили б/у</a>
                        <div class="window hide">
                            <div class="iframe"><iframe></iframe></div>
                            <div style="width: 340px;" class="wrapper">
                                <p class="headbar bold">
                                    <a href="/search">
                                        Автомобили б/у
                                    </a>
                                </p>
                                <ul class="column unordered-list">
                                    <li><a href="/legkovie/" title="Легковые" >Легковые</a></li>
                                    <li><a href="/moto/" title="Мото" >Мото</a></li>
                                    <li><a href="/vodnyj_transport/" title="Водный транспорт" >Водный транспорт</a></li>
                                    <li><a href="/spectehnika/" title="Спецтехника">Спецтехника</a></li>
                                    <li><a href="/trailer/" title="Прицепы">Прицепы</a></li>
                                    <li><a href="/truck/" title=" Грузовики"> Грузовики</a></li>
                                    <li><a href="/bus/" title="Автобусы" >Автобусы</a></li>
                                    <li><a href="/autohouse/" title="Автодома">Автодома</a></li>
                                    <li><a href="/air_transport/" title="Воздушный транспорт" >Воздушный транспорт</a></li>

                                </ul>
                                <ul class="column unordered-list" >
                                    <li><a href="/search.html" title="Поиск авто" >Поиск авто</a></li>
                                    <li><a href="/hots/" title="Горячие предложения" >Горячие предложения</a></li>
                                    <li><a href="/retro/" title="Ретро автомобили" >Ретро автомобили</a></li>
                                    <li><a href="/autointer/" title="Авто из-за рубежа" >Авто из-за рубежа</a></li>
                                    <li><a href="/avtovikup/" title="Автовыкуп">Автовыкуп</a></li>
                                    <li><a href="/kredit_auto/" class="new" title="Кредитные авто" >Кредитные авто</a></li>
                                    <li><a href="/newauto/Отзывы/Каталог/" class="new" title="Отзывы об авто" >Отзывы об авто</a></li>
                                    <li  ><a href="/diagnostika-promo/" class="new" title="Проверенные авто" >Проверенные авто</a></li>
                                    <li><a href="/driven-cars/" class="new" title="Пригнанные авто">Пригнанные авто</a></li>
                                </ul>
                                <div class="menu__bottom-panel">
                                    <a class="link-add" href="/add_auto.html" title="Добавить объявление" >
                                        Добавить объявление
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tabs" tab="3">
                        <a href="/newauto/" >Новые авто</a>
                        <div class="window hide">
                            <div class="iframe"><iframe></iframe></div>
                            <div style="width: 345px;" class="wrapper">
                                <p class="headbar bold">
                                    <a href="/newauto/">Новые авто</a>
                                </p>
                                <ul class="column unordered-list">
                                    <li><a href="/newauto/" title="Поиск новых авто">Поиск новых авто</a></li>
                                    <li  ><a href="/new_auto/master_search/" title="Мастер поиска" >Мастер поиска</a></li>
                                    <li><a href="/newauto/catalogue/" title="Каталог новых авто">Каталог новых авто</a></li>
                                    <li><i class="icon-reliable-partner"></i><a href="/reliable-partner/" title="Надежный партнер" >Надежный партнер</a></li>
                                </ul>
                                <ul class="column unordered-list">
                                    <li><a href="/newauto/avtosaloni/" title="Автосалоны" >Автосалоны</a></li>
                                    <li><a class="new" href="/newauto/motosaloni/" title="Мотосалоны" >Мотосалоны</a></li>
                                    <li><a href="/news/actions/" title="Акции автосалонов" >Акции автосалонов</a></li>
                                    <li><a href="/newauto/Отзывы/Каталог/" class="new" title="Отзывы об авто" >Отзывы об авто</a></li>
                                </ul>
                                <div class="menu__bottom-panel">
                                    <a class="link-add" href="/avtosaloni/addinfo/" title="Добавить Автосалон"  >
                                        Добавить Автосалон
                                    </a>
                                    <em class="mdash">|</em>
                                    <a class="link-add" href="/motosalon/addinfo/" title="Добавить Мотосалон" >
                                        Добавить Мотосалон
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tabs" tab="4">
                        <a href="/all_for_auto/">Все для авто</a>
                        <div class="window hide">
                            <div class="iframe"><iframe></iframe></div>
                            <div style="width: 565px;" class="wrapper">
                                <div class="column" style="width: 155px">
                                    <dl class="unordered-list">
                                        <dt>Сервисы</dt>
                                        <dd><a href="/avtorazborka/" title="Авторазборка" >Авторазборка</a></dd>
                                        <dd>
                                            <i class="icon-reliable-partner"></i>
                                            <a href="/reliable-partner/autorazborka/" onclick="_gaq.push(['_trackEvent', 'Аvtorazborka', 'AllForAuto', 'Сlick_on_reliable_partner'])">Надежный партнер</a>
                                        </dd>
                                        <dd><a href="/avtorazborka/#stolzakazov" onclick="_gaq.push(['_trackEvent', 'Stol_Zakazov_Zapch', 'Add_Aplication', 'Main_AUTO.ria.ua']);" title="Стол заказов запчастей">Стол заказов запчастей</a></dd>
                                        <dd><a href="/avtovikup/" title="Автовыкуп">Автовыкуп</a></dd>
                                        <dd><a href="/autolombardy/"  title="Автоломбарды" >Автоломбарды</a></dd>
                                        <dd><a href="/autoservice/" title="Автосервисы" >Автосервисы</a></dd>
                                        <dd><a href="/strahovanie/" title="Автострахование" >Автострахование</a></dd>
                                        <dd><a href="/rastamozhka_avto/" title="Растаможка авто" >Растаможка авто</a></dd>
                                    </dl>
                                </div>

                                <div class="column">
                                    <dl class="unordered-list">

                                        <dt>
                                        Товары от
                                        <a href="http://market.auto.ria.ua" >
                                            <i class="ico-market"></i>
                                        </a>
                                        </dt>
                                        <dd><a href="http://market.auto.ria.ua/shina" title="Шины" >Шины</a></dd>
                                        <dd><a href="http://market.auto.ria.ua/diski" title="Диски" >Диски</a></dd>
                                        <dd><a href="http://market.auto.ria.ua/car_seats/" title="Детские автокресла" >Детские автокресла</a></dd>
                                        <dd><a href="http://market.auto.ria.ua/avtochehlu" title="Чехлы на сиденья" >Чехлы на сиденья</a></dd>
                                        <dd><a href="http://market.auto.ria.ua/kovriki/" title="Коврики" >Коврики</a></dd>
                                        <dd><a href="http://market.auto.ria.ua/farkop/" title="Фаркопы" o>Фаркопы</a></dd>

                                        <dt>&nbsp;</dt>
                                        <dd><a href="http://zapchasti.ria.ua/" title="Запчасти">Запчасти</a></dd>
                                        <dd><a href="http://dom.ria.ua/garage/" title="Гаражи" target="_blank" >Гаражи</a></dd>
                                        <dd><a href="/document/" title="Автодокументы" >Автодокументы</a></dd>
                                    </dl>
                                </div>

                                <div class="column" style="width: 195px">
                                    <dl class="unordered-list">
                                        <dt>Полезное</dt>
                                        <dd><a href="/avtoshkola/"  title="Автошколы" >Автошколы</a></dd>
                                        <dd><a href="/online_pdd/"  title="Билеты ПДД онлайн" >Билеты ПДД онлайн</a></dd>
                                        <dd><a href="/golink/?http://vk.com/board6499791" title="Обсуждения" title="Обсуждения">Обсуждения</a></dd>
                                        <dd><a href="/humor/" title="Автоюмор" >Автоюмор</a></dd>
                                        <dd><a href="/autoclubs/" title="Автоклубы" >Автоклубы</a></dd>

                                        <dd  ><a href="http://link.auto.ria.ua/" title="Автосайты" >Автосайты</a></dd>

                                        <dd><a href="/automagazine/" title="Журналы" >Журналы</a></dd>

                                        <dd  ><a href="http://lanos.com.ua/" title="Все про Lanos">Все про Lanos</a></dd>

                                        <dd><a href="/first_auto/"  title="Покупаем первый автомобиль" >Покупаем первый автомобиль</a></dd>
                                        <dd><a href="/newauto/Отзывы/Каталог/" class="new" title="Отзывы об авто" >Отзывы об авто</a></dd>
                                    </dl>
                                </div>

                                <div class="menu__bottom-panel">
                                    <a  href="/help/" title="Помощь" >Помощь</a>
                                    <em  class="mdash">|</em>
                                    <a href="/news/novinki/" title="Нововведения" >Нововведения</a>
                                    <em class="mdash">|</em>
                                    <a class="new" href="/?target=view&event=lic" title="Соглашение о предоставлении услуг" >Соглашение о предоставлении услуг</a>

                                </div>
                                <div class="menu__bottom-panel">
                                    <a class="link-add"  href="/document/add.html" title="Добавить Автодокумент" >Добавить Автодокумент</a>
                                    <em class="mdash">|</em>
                                    <a class="link-add" href="http://www.ria.ua/advertisement/addstep1" title="Добавить запчасть" >Добавить запчасть</a>
                                </div>


                            </div>
                        </div>

                    </div>
                    <div class="tabs" tab="5">
                        <a href="/news/" >Новости</a>
                        <strong class="blue"></strong>
                        <div class="window hide">
                            <div class="iframe"></div>
                            <div class="wrapper" style="width: 412px;">




                                <div class="column" style="min-width: 90px">
                                    <dl class="unordered-list">
                                        <dt>
                                        <a href="/news/" >Все новости</a>
                                        </dt>



                                        <dd>

                                            <a href="/news/events/" >События</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/auto/" >Автомобили</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/autobusiness/" >Автобизнес</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/autolaw/" >Автозакон</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/actions/" >Акции</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/test-drive/" >Тест-драйвы</a>

                                        </dd>


                                    </dl>

                                </div>
                                <div class="column" style="width: 165px">
                                    <dl class="unordered-list">
                                        <dt>&nbsp;</dt>





                                        <dd>

                                            <a href="/news/autoservice_technology/"  >Автосервис и Технологии</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/about_us/" >О нас пишут</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/avtoblog/" >Автоблоги</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/novinki/" >Нововведения</a>

                                        </dd>



                                    </dl>
                                </div>
                                <div class="column" style="min-width: 105px; padding-right: 0;">
                                    <dl class="unordered-list">
                                        <dt>&nbsp;</dt>





                                        <dd>

                                            <a href="/news/subaru/" >Все о Subaru</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/bmw/" >Все o BMW</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/mini/" >Все о MINI</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/journals/" >Онлайн журнал</a>

                                        </dd>





                                        <dd>

                                            <a href="/news/konkurs/" >Конкурсы</a>

                                        </dd>





                                    </dl>
                                </div>






                            </div>
                        </div>




                    </div>
                    <div class="tabs" >
                        <a href="/notepad.html" >
                            <i class="icon-star-tab"></i> Блокнот
                            <!--            FIX THIS to JavaScript-->
                            <!--            # if expr="$bookmarks_count!=0"
                                            <strong class="blue">
                                                #echo var="bookmarks_count"
                                            </strong>
                                        # endif -->
                        </a>
                    </div>

                    <span class="area">
                        <i class="ico-new"></i>
                        <a href="/news/konkurs/208892/" target="_blank" class="insert-element"
                           onclick="_gaq.push(['_trackEvent', 'Whats_New', 'Click_on_konkurs_vuso', '/']);">
                            Выиграй навигатор

                        </a>
                        <!-- Page load array script time : 0.012784004211426
                        -->
                    </span>
                </div>


                <!--   .END main menu   -->


                <h2 class="breadcrumbs">
                    <a class="item" href="/" title="Продажа автомобилей">Автомобили</a>
                    <a class="item" href="/mymenu/">Моё меню</a>
                    Мои автомобили</h2>

                <?php echo $this->layout()->content; ?>

                <div class="window-fixed hide" id="houses_popup"></div>
                <div id="final_page__thanks_popup_container" class="popup uarr __right" style=" display: none; width: 350px; right: 50px">
                    <div class="wrapper grid" id="final_page__thanks_popup_wrapper"></div>
                </div>
                <div class="popup uarr __right" style="display: none; width: 350px;" id="user_menu__group_deleting_container">
                    <div class="wrapper grid" id="user_menu__group_deleting_wrapper"></div>
                </div>            </div>

            <a href="/impressions" class="feedback"></a>
        </div>
        <!--    .BEGIN FOOTER    -->
        <footer>
            <div class="container">

                <div class="footer-menu">

                    <div class="copyright">
                        &copy; 2004-2013 RIA.ua.<br />
                        Все права защищены
                    </div>

                    <div class="footer-signature">

                        <nav class="menu-footer">
                            <a class="item" href='http://www.ria.ua/'>Объявления</a>
                            <a class="item active" href='http://auto.ria.ua/'>Автомобили</a>
                            <a class="item" href='http://dom.ria.ua/'>Недвижимость</a>
                            <a class="item" href='http://rabota.ria.ua/'>Работа</a>

                            <a class="item" href="http://hotels.ria.ua/">Гостиницы</a>
                            <a class="item" href="http://avia.ria.ua/">Билеты</a>


                        </nav>

                        <div class="clear"></div>

                        <div class="left-bar__footer">

                            <a href="http://auto.ria.ua/price/">Реклама на сайте</a><br />

                            <!--i class="icon-mobile"></i-->
                            <a href="http://m.auto.ria.ua/">Мобильная версия</a><br />

                            <!--i class="icon-bezpeka"></i-->
                            <a href="http://bezpeka.ria.ua/">Безопасные сделки</a>


                        </div>

                        <div class="signature__footer">


                            <div class="right-bar__footer">
                                <a target="_blank" title="Prom.ua — здесь находят клиентов (откроется в новом окне)" href="http://prom.ua">Prom.ua</a><br />


                                <a target="_blank" href="/map/">Карта сайта</a><br/>

                            </div>

                            <a href="http://auto.ria.ua/question/my_active_ads/">Помощь</a><br />
                            <a target="_blank" href="http://auto.ria.ua/privacy-policy/">Политика конфиденциальности</a><br />
                            <a href="http://cobrand.ria.ua/">Партнерские программы</a>



                        </div>

                    </div>
                </div>
                <!-- Yandex.Metrika counter -->
                <script type="text/javascript">
                        (function(d, w, c) {
                            (w[c] = w[c] || []).push(function() {
                                try {

                                    w.yaCounter91244 = new Ya.Metrika({id: 91244,
                                        webvisor: true,
                                        clickmap: true});
                                } catch (e) {
                                }
                            });

                            var n = d.getElementsByTagName("script")[0],
                                    s = d.createElement("script"),
                                    f = function() {
                                n.parentNode.insertBefore(s, n);
                            };
                            s.type = "text/javascript";
                            s.async = true;
                            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

                            if (w.opera == "[object Opera]") {
                                d.addEventListener("DOMContentLoaded", f);
                            } else {
                                f();
                            }
                        })(document, window, "yandex_metrika_callbacks");
                </script>


                <noscript><div><img src="//mc.yandex.ru/watch/91244" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

                <!-- /Yandex.Metrika counter -->


                <!-- (C)2000-2013 Gemius SA - gemiusAudience / ria.ua / main_AUTO.ria.ua -->
                <script type="text/javascript">
                    <!--//--><![CDATA[//><!--
                    var pp_gemius_identifier = new String('1vA6D_NhUvtTkwZMEn6w06RunDPikRgddAeCLxl50M7.Q7');
                    //--><!]]>
                </script>
                <script type="text/javascript" src="http://www.ria.ua/gemius/xgemius.js"></script>




                <div id="vk_api_transport"></div>

                <!-- MMI CMeter -->

                <noscript>
                <img
                    src="http://juke.mmi.bemobile.ua/bug/pic.gif?siteid=auto.ria.ua"
                    style="position:absolute;left:-1000px;"
                    alt=""
                    />
                </noscript>
                <script language="javascript">
                    var tns_already;
                    if ("undefined" == typeof(tns_already) || null == tns_already || 0 == tns_already)
                    {
                        tns_already = 1;
                        var i = new Image();
                        i.src = "http://juke.mmi.bemobile.ua/bug/pic.gif?siteid=auto.ria.ua&j=1&" + Math.random();

                        (function() {
                            var p = document.getElementsByTagName('head')[0];
                            var s = document.createElement("script");
                            s.type = "text/javascript";
                            s.src = "http://source.mmi.bemobile.ua/id/id.js";
                            s.async = true;
                            s.onload = s.onreadystatechange = function() {
                                if (!("readyState" in s) || /loaded|complete/.test(s.readyState)) {
                                    s.onload = s.onreadystatechange = null;
                                    var s2 = document.createElement("script");
                                    s2.type = "text/javascript";
                                    s2.src = "http://source.mmi.bemobile.ua/cm/cmeter.js";
                                    s2.async = true;
                                    var p = document.getElementsByTagName('head')[0];
                                    p.appendChild(s2);
                                }
                            }
                            p.appendChild(s);
                        })();
                    }
                    ;
                </script>

                <!-- /MMI CMeter -->

            </div>

        </footer>
    </body>
</html>